#**Violencia contra la mujer en México.** 

---
##Proyecto BEDU-Santander: Python.

**Equipo no.17:**

*   Bernal Rodríguez Carolina.
*   Velázquez Valdez Carlos.
*   Zamudio Guzmán Linette.




##**Contexto e importancia.**

Las Naciones Unidas definen la violencia contra la mujer como "*todo acto de violencia de género que resulte, o pueda tener como resultado un daño físico, sexual o psicológico para la mujer, inclusive las amenazas de tales actos, la coacción o la privación arbitraria de libertad, tanto si se producen en la vida pública como en la privada*"(OMS,2017).


> **"*Las estimaciones mundiales publicadas por la OMS indican que alrededor de una de cada tres (35%) mujeres en el mundo han sufrido violencia física y/o sexual de pareja o violencia sexual por terceros en algún momento de su vida.*"(OMS,2017).**

Actualmente las niñas y mujeres sufren diversos tipos de violencia (en sus múltiples manifestaciones) en diversos  ámbitos de su vida como lo son: el hogar, el espacio público, la escuela, el trabajo, el ciberespacio,  la política, entre otros. En particular,no podemos ignorar que la mujer aún padece situaciones de violencia y maltrato especialmente por su pareja y en ocasiones en su propio hogar.
 >**"*Un 38% de los asesinatos de mujeres que se producen en el mundo son cometidos por su pareja masculina.*"(OMS,2017).**
<p align= "justify">
La violencia en contra de  la mujer ha sido y sigue siendo, por desgracia,un problema de alcance internacional. Como todo problema, parte de la solución se encuentra en el ámbito de la prevención primaria, a fin de que dejen de existir actos de violencia  y e impedir que estos lleguen a reproducirse.Para propiciar cambios significativos y duraderos es importante promulgar y aplicar leyes que promuevan la igualdad de género mediante un enfoque multisectorial. Esto es vital, ya que la desigualdad de género es escalable a su expresión más condenable, la violencia contra la mujer. De tal forma que, mediante la erradicación de la desiguldad de género podremos eliminar con mayor eficacia la violencia contra la mujer.

###**Magnitud del problema en México.**
<p align= "justify">
En materia de desigualdad de género, nuestro país ocupa la posición 72 de un total de 186 naciones. Con un índice de 0.382,México se encuentra arriba del promedio de Europa y Asia Central y por debajo del promedio de América Latina (0.419) y de la media mundial en esta materia (0.463)(Moctezuma, D. Narro,J.Orozco,L, 2014).</p>

<p align= "justify">
<img src="https://delphos.nu/site/wp-content/uploads/2017/11/DCVCM_1.jpg" width="500px" style="center"/>

<p align= "justify">
Al problema de desigualdad y discriminación que enfrentan las mujeres en nuestra sociedad, se suman las violencias de tipo físico, sexual o psicológico.Vivimos un panorama en el que es imposible permanecer indiferente ante el alarmante crecimiento de la trata, de  la esclavitud sexual de las mujeres y de los feminicidios. De acuerdo al INEGI, de 2007 a 2010 la tasa de muertes por feminicidios aumentó más del doble al pasar de 2 a 4.4 por cada cien mil fallecimientos (Moctezuma, D. Narro,J.Orozco,L, 2014).

###**¿Qué sucede en la actualidad con la violencia de género en México?**
Debido a la situación que estamos viviendo en la actualidad, durante la pandemia por COVID-19,estamos ante una nueva urgencia para la acción. Las medidas de aislamiento y distanciamiento social del confinamiento, junto con el estrés, la ansiedad y las preocupaciones sociales o económicas, han aumentado el riesgo de violencia en el hogar lo que llevó a que los registros de violencia contra la mujer en el hogar amentara 60% en México, de acuerdo con cifras de la Organización de las Naciones Unidas (ONU).

A medida que estos factores de riesgo de violencia aumentan, disminuyen los factores de protección, incluido el acceso a los servicios de salud y protección necesarios. 

En ese sentido, Juliette Bonnafé, integrante del equipo de ONU Mujeres en México, señaló que este dato lo apunta el registro de llamadas a las líneas de apoyo que tiene esta institución para atender a mujeres que enfrentan esta situación.(https://www.forbes.com.mx/women-violencia-mujer-hogar-aumenta-60-pandemia/)

##**Información sobre soluciones ya existentes.**

Dado que el tema de violencia contra la mujer se ha vuelto de relevancia a nivel mundial por la gran cantidad de mujeres que lo sufren, diversos grupos tanto gubernamentales como no gubernamentales se han dado a la tarea de realizar análisis de datos.

Un ejemplo es *La Data*. Grupo que se dedica a realizar periodismo y sustentarlo a través de análisis de datos. Realizó un análisis sobre violencia hacia las mujeres en el cuál se incluye el costo que representa este tipo de violencia, el ámbito en el que ocurre, información sobre el número de feminicidios, tipo de ayuda que solicitaron las víctimas. Para más información: http://www.ladata.mx/violenciamujeres/


##**Acercamiento al problema.**

En relación a lo anteriormente expuesto, nos planteamos las siguientes ***preguntas*** para lograr comprender, dimensionalizar y analizar el problema de **violencia contra la mujer en México**:

- ¿En qué delegación de la CDMX ocurre el mayor número de delitos contra la mujer?
- ¿Cúal es el delito con mayor número de denuncias relacionado a violencia contra la mujer?
- ¿Cómo se ha reflejado la violencia de género en los últimos años en la CDMX?
- ¿Cómo se relaciona la situación social (escolaridad, ocupación, estado civil) con la violencia de género en México?
-¿Cuáles son las entidades con mayor número de delitos en general (violencia de género)?
-¿Cuáles son los delitos relacionados con violencia de género con mayor número de víctimas en México?
-¿Cual ha sido la tendencia de abuso sexual/violación/violencia de genero en México del 2015-2020?
-¿Cómo ha ido aumentando el número de feminicidios en México con el paso de los años?¿En qué entidades se han visto más reportes de estos?
  

##**Búsqueda de Bases de Datos.**

De la búsqueda de información y contexto del tema fue posible plantear la problemática a investigar, posteriormente, con el objetivo de analizarla a fondo se planteron preguntas de investigación con las cuales se espera obtener respuestas claves y conclusiones.

Así, el siguiente paso es encontrar las ***bases de datos*** adecuadas para responder dichas preguntas. Dichas bases de datos se encuentran localizadas en el repositorio de Github del Equipo en la carpera **Datasets**. Disponibles en:https://github.com/CarolinaBer/Proyecto_Python_Equipo17 en formato .zip.     

`llamadas_poblacion_gral_cdmx.csv`Contiene  la información de las llamadas realizadas al servicio LOCATEL desde noviembre de 2016. A PARTIR DE NOVIEMBRE DEL 2020 LA BASE DE DATOS DE LÍNEA MUJERES FUE COMPLETADA PARA MOSTRAR TODOS LOS SERVICIOS OFRECIDOS PARA LA POBLACIÓN EN GENERAL. <br>
`carpetas_investigacion_cdmx_2016_2020.csv` Contiene la información actualizada de las carpetas de investigación de la Fiscalía General de Justicia (FGJ) de la Ciudad de México a partir de enero de 2016. <br>
`vitimas_carpeta_cdmx_2016_2020.csv` Contiene la información actualizada de las víctimas de los delitos en las carpetas de investigación de la Fiscalía General de Justicia (FGJ) de la Ciudad de México a partir de enero de 2019. <br>
`municipal_delitos_nacional_2015_ene2021.csv` Contiene las cifras de incidencia delictiva municipal, 2015 - enero 2021.  <br>
`victimas_nacional_2015_ene2021.csv` Contiene datos de las víctimas registradas a nivel nacional durante 2015-enero 2021. <br>
`personas_desaparecidas_al2018_ff.csv`  Contiene el total de registros de personas relacionadas con averiguaciones previas y carpetas de investigación del fuero federal iniciadas en el periodo comprendido entre enero de 2014 y abril de 2018, y que permanecen sin localizar al corte del 30 de abril de 2018. <br>
`personas_desaparecidas_al2018_fc.csv` Contiene el total de registros de personas relacionadas con averiguaciones previas, carpetas de investigación o actas circunstanciadas del fuero común que permanecen sin localizar al corte del 30 de abril del 2018. <br>


##**Limpieza y análisis de las Bases de Datos.** 

Cada una de las bases de datos requerirá un procedimiento de limpieza particular para poder analizar los datos, en general el procedimiento de limpieza consta de lo siguiente:


*   Eliminar valores perdidos NaN.
*   Renombramiento de columnas.
*   Realizar agrupaciones pertinentes para lograr obtener un análisis estadístico.





---



### **Limpieza y análisis de `llamadas_poblacion_gral_cdmx.csv`**

En esta base podrás encontrar toda la información de las llamadas realizadas al servicio LOCATEL desde noviembre de 2016. Dicha información se actualiza semanalmente a partir del 6 de abril de 2020. **A PARTIR DE NOVIEMBRE DEL 2020 LA BASE DE DATOS DE LÍNEA MUJERES FUE COMPLETADA PARA MOSTRAR TODOS LOS SERVICIOS OFRECIDOS PARA LA POBLACIÓN EN GENERAL.**

In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np 

In [ ]:
#Lectura de los archivos .csv . NOTA: Los archivos se encuentran en una carpeta de Drive que facilita su lectura en este Notebook.
#Adicionalmente cada dataset analizado se encuentra en formato .zip en el Github del equipo  disponibles para su descarga.
#Fue obtenido de [I] Gobierno CDMX.Datos Abiertos.
ruta_archivo = "/content/drive/MyDrive/Datasets/Datasets/llamadas_poblacion_gral_cdmx.csv"
llamadas_poblacion_gral = "llamadas_poblacion_gral.csv"
df_llamadas_poblacion_cdmx = pd.read_csv(ruta_archivo,encoding = "latin1")

### **Explorando el dataset.**

In [ ]:
#Exploración del dataset 
df_llamadas_poblacion_cdmx.head(3) #Se puede observar que existen valores NaN a limpiar y algunos datos disponibles

FOLIO  FECHA_ALTA  AÑO_ALTA  ...  TEMATICA_5  TEMATICA_6  TEMATICA_7
0  3011.0  2016-11-01      2016  ...         NaN         NaN         NaN
1  3012.0  2016-11-01      2016  ...         NaN         NaN         NaN
2  3013.0  2016-11-01      2016  ...         NaN         NaN         NaN

[3 rows x 28 columns]

In [ ]:
#Exploración del dataset
print(df_llamadas_poblacion_cdmx.dtypes) #Observamos todas las columnas y el tipo de dato que almacenan 
df_llamadas_poblacion_cdmx.shape  #Para obtener el número de registros y columnas 

FOLIO                float64
FECHA_ALTA            object
AÑO_ALTA               int64
MES_ALTA               int64
DÍA_ALTA               int64
HORA_ALTA              int64
SEXO                  object
EDAD                   int64
ESTADO_CIVIL          object
OCUPACION             object
ESCOLARIDAD           object
ESTADO_USUARIA        object
MUNICIPIO_USUARIA     object
COLONIA_USUARIA       object
CP_USUARIA           float64
ESTADO_HECHOS         object
MUNICIPIO_HECHOS      object
COLONIA_HECHOS        object
CP_HECHOS            float64
ORIGEN                object
SERVICIO              object
TEMATICA_1            object
TEMATICA_2            object
TEMATICA_3            object
TEMATICA_4            object
TEMATICA_5            object
TEMATICA_6            object
TEMATICA_7            object
dtype: object


(868073, 28)

In [ ]:
df_llamadas_poblacion_cdmx.info() #Obteniendo la información del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868073 entries, 0 to 868072
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   FOLIO              868072 non-null  float64
 1   FECHA_ALTA         868073 non-null  object 
 2   AÑO_ALTA           868073 non-null  int64  
 3   MES_ALTA           868073 non-null  int64  
 4   DÍA_ALTA           868073 non-null  int64  
 5   HORA_ALTA          868073 non-null  int64  
 6   SEXO               868073 non-null  object 
 7   EDAD               868073 non-null  int64  
 8   ESTADO_CIVIL       743086 non-null  object 
 9   OCUPACION          734638 non-null  object 
 10  ESCOLARIDAD        719520 non-null  object 
 11  ESTADO_USUARIA     868073 non-null  object 
 12  MUNICIPIO_USUARIA  867188 non-null  object 
 13  COLONIA_USUARIA    867188 non-null  object 
 14  CP_USUARIA         868061 non-null  float64
 15  ESTADO_HECHOS      179985 non-null  object 
 16  MU

In [ ]:
df_llamadas_poblacion_cdmx.columns #Obteniendo la información de las columnas que contiene.

Index(['FOLIO', 'FECHA_ALTA', 'AÑO_ALTA', 'MES_ALTA', 'DÍA_ALTA', 'HORA_ALTA',
       'SEXO', 'EDAD', 'ESTADO_CIVIL', 'OCUPACION', 'ESCOLARIDAD',
       'ESTADO_USUARIA', 'MUNICIPIO_USUARIA', 'COLONIA_USUARIA', 'CP_USUARIA',
       'ESTADO_HECHOS', 'MUNICIPIO_HECHOS', 'COLONIA_HECHOS', 'CP_HECHOS',
       'ORIGEN', 'SERVICIO', 'TEMATICA_1', 'TEMATICA_2', 'TEMATICA_3',
       'TEMATICA_4', 'TEMATICA_5', 'TEMATICA_6', 'TEMATICA_7'],
      dtype='object')

### **Encontrando y limpiando valores NaN.** 

In [ ]:
#Identificando los valores perdidos por columna
df_llamadas_cdmx_NaN = df_llamadas_poblacion_cdmx.isna().sum(axis=0)
print(df_llamadas_cdmx_NaN)

FOLIO                     1
FECHA_ALTA                0
AÑO_ALTA                  0
MES_ALTA                  0
DÍA_ALTA                  0
HORA_ALTA                 0
SEXO                      0
EDAD                      0
ESTADO_CIVIL         124987
OCUPACION            133435
ESCOLARIDAD          148553
ESTADO_USUARIA            0
MUNICIPIO_USUARIA       885
COLONIA_USUARIA         885
CP_USUARIA               12
ESTADO_HECHOS        688088
MUNICIPIO_HECHOS     688088
COLONIA_HECHOS       688088
CP_HECHOS            688088
ORIGEN                    0
SERVICIO                  0
TEMATICA_1                0
TEMATICA_2            21110
TEMATICA_3           114072
TEMATICA_4           490796
TEMATICA_5           641760
TEMATICA_6           676412
TEMATICA_7           705614
dtype: int64


In [ ]:
# Ordenamos los valores perdidos de menor a mayor
df_llamadas_cdmx_NaN[df_llamadas_cdmx_NaN>0].sort_values()

FOLIO                     1
CP_USUARIA               12
MUNICIPIO_USUARIA       885
COLONIA_USUARIA         885
TEMATICA_2            21110
TEMATICA_3           114072
ESTADO_CIVIL         124987
OCUPACION            133435
ESCOLARIDAD          148553
TEMATICA_4           490796
TEMATICA_5           641760
TEMATICA_6           676412
MUNICIPIO_HECHOS     688088
COLONIA_HECHOS       688088
ESTADO_HECHOS        688088
CP_HECHOS            688088
TEMATICA_7           705614
dtype: int64

In [ ]:
#Tenemos que eliminar las columnas que tienen más de la mitad de valores perdidos 
df_llamadas_cdmx_modificado = df_llamadas_poblacion_cdmx.drop(columns=['TEMATICA_4','TEMATICA_5', 'TEMATICA_6', 'MUNICIPIO_HECHOS', 'COLONIA_HECHOS','ESTADO_HECHOS','CP_HECHOS','TEMATICA_7'])

In [ ]:
#Volvemos a observar los valores perdidos ya del dataset modificado ordenados de menor a mayor 
df_llamadas_cdmx__modificado_NaN = df_llamadas_cdmx_modificado.isna().sum(axis=0)
df_llamadas_cdmx__modificado_NaN[df_llamadas_cdmx__modificado_NaN>0].sort_values()

FOLIO                     1
CP_USUARIA               12
MUNICIPIO_USUARIA       885
COLONIA_USUARIA         885
TEMATICA_2            21110
TEMATICA_3           114072
ESTADO_CIVIL         124987
OCUPACION            133435
ESCOLARIDAD          148553
dtype: int64

In [ ]:
# Ahora las columnas CP_USUARIA, MUNICIPIO_USUARTIA y  COLONIA_USUARIA tienen aproximadamente el 10% de valores perdidos, con la finalidad de no perder 
# estos datos pueden modificarse 

df_llamadas_cdmx_modificado['CP_USUARIA'] = df_llamadas_cdmx_modificado['CP_USUARIA'].fillna('Desconocido')
df_llamadas_cdmx_modificado['MUNICIPIO_USUARIA'] = df_llamadas_cdmx_modificado['MUNICIPIO_USUARIA'].fillna('Desconocido')
df_llamadas_cdmx_modificado['COLONIA_USUARIA'] = df_llamadas_cdmx_modificado['COLONIA_USUARIA'].fillna('Desconocido')

#Nuevamente checamos los valores NaN que nos faltan

df_llamadas_cdmx__modificado_NaN = df_llamadas_cdmx_modificado.isna().sum(axis=0)
df_llamadas_cdmx__modificado_NaN[df_llamadas_cdmx__modificado_NaN>0].sort_values()


FOLIO                1
TEMATICA_2       21110
TEMATICA_3      114072
ESTADO_CIVIL    124987
OCUPACION       133435
ESCOLARIDAD     148553
dtype: int64

In [ ]:
#Limpiando los NaN faltantes, limpiando las filas que tengan mínimo 1 valor NaN.
df_llamadas_cdmx_modificado  = df_llamadas_cdmx_modificado.dropna(axis=0, how='any')

#Confirmamos que ya no exista ningún valor perdidio 
df_llamadas_cdmx__modificado_NaN = df_llamadas_cdmx_modificado.isna().sum(axis=0)
print(df_llamadas_cdmx__modificado_NaN)

FOLIO                0
FECHA_ALTA           0
AÑO_ALTA             0
MES_ALTA             0
DÍA_ALTA             0
HORA_ALTA            0
SEXO                 0
EDAD                 0
ESTADO_CIVIL         0
OCUPACION            0
ESCOLARIDAD          0
ESTADO_USUARIA       0
MUNICIPIO_USUARIA    0
COLONIA_USUARIA      0
CP_USUARIA           0
ORIGEN               0
SERVICIO             0
TEMATICA_1           0
TEMATICA_2           0
TEMATICA_3           0
dtype: int64


In [ ]:
#Observamos el dataset y nos damos cuenta de que los índices no corresponden por lo que hay que resetearlo.
df_llamadas_cdmx_modificado.head()

FOLIO  ...                TEMATICA_3
1  3012.0  ...  REFERENCIA INSTITUCIONAL
2  3013.0  ...              ABUSO SEXUAL
3  3014.0  ...        VIOLENCIA FAMILIAR
5  3016.0  ...  REFERENCIA INSTITUCIONAL
6  3017.0  ...             DÍAS FESTIVOS

[5 rows x 20 columns]

In [ ]:
# Resetendo el índice para que sea compatible con el nuevo dataset y corroboramos.
df_llamadas_cdmx_modificado_limpio = df_llamadas_cdmx_modificado.reset_index(drop=True)
df_llamadas_cdmx_modificado_limpio.head() #¡Listo! Ya tenemos nuestro Dataset libre de valores NaN

FOLIO  ...                TEMATICA_3
0  3012.0  ...  REFERENCIA INSTITUCIONAL
1  3013.0  ...              ABUSO SEXUAL
2  3014.0  ...        VIOLENCIA FAMILIAR
3  3016.0  ...  REFERENCIA INSTITUCIONAL
4  3017.0  ...             DÍAS FESTIVOS

[5 rows x 20 columns]

### **Modificando el nombre de las columnas.**

In [ ]:
#Primero cambiaremos todos los nombres de las columnas a minúsculas. 
df_llamadas_cdmx_modificado_limpio.columns= df_llamadas_cdmx_modificado_limpio.columns.str.strip().str.lower()
df_llamadas_cdmx_modificado_limpio.columns

Index(['folio', 'fecha_alta', 'año_alta', 'mes_alta', 'día_alta', 'hora_alta',
       'sexo', 'edad', 'estado_civil', 'ocupacion', 'escolaridad',
       'estado_usuaria', 'municipio_usuaria', 'colonia_usuaria', 'cp_usuaria',
       'origen', 'servicio', 'tematica_1', 'tematica_2', 'tematica_3'],
      dtype='object')

In [ ]:
#Como ahora se incluye a la población en general, hay que modificar "usuaria" y modificar los nombres de tematica y origen a otros más comprensibles
#Creamos un diccionario con el nombre de las columnas viejas y nuevas
nombre_columnas_llamadas_cdmx = {
    'día_alta':'dia_alta',
    'estado_usuaria':'estado',
    'municipio_usuaria':'municipio',
    'colonia_usuaria':'colonia',
    'cp_usuaria' : 'cp',
    'origen':'plataforma',
    'tematica_1': 'razon_llamada_gral',
    'tematica_2': 'razon_llamada_especifica',
    'tematica_3': 'llamada_detalles'
}


In [ ]:
#Modificamos el nombre de las columnas del dataframe
df_llamadas_cdmx_limpio_renombrado = df_llamadas_cdmx_modificado_limpio.rename(columns=nombre_columnas_llamadas_cdmx)

In [ ]:
# ¡Listo! Tenemos nuestro dataframe limpio y renombrado 
df_llamadas_cdmx_limpio_renombrado.head(3)

folio  ...          llamada_detalles
0  3012.0  ...  REFERENCIA INSTITUCIONAL
1  3013.0  ...              ABUSO SEXUAL
2  3014.0  ...        VIOLENCIA FAMILIAR

[3 rows x 20 columns]

In [ ]:
#Vamos a modificar los datos del dataset para que aparezcan en minúsculas
# Para ello es necesario utilizar applymap para encontrar las cadenas de caracteres que se pueden modificar junto con la función lambda
df_llamadas_cdmx_limpio_renombrado = df_llamadas_cdmx_limpio_renombrado.applymap(lambda texto: texto.lower() if type(texto)== str else texto)
df_llamadas_cdmx_limpio_renombrado.head(3)

folio  ...          llamada_detalles
0  3012.0  ...  referencia institucional
1  3013.0  ...              abuso sexual
2  3014.0  ...        violencia familiar

[3 rows x 20 columns]

In [ ]:
#Recordando el tipo de datos que tenemos 
print(df_llamadas_cdmx_limpio_renombrado.shape) #Nuevo tamaño de nuestro dataset
df_llamadas_cdmx_limpio_renombrado.dtypes

(624850, 20)


folio                       float64
fecha_alta                   object
año_alta                      int64
mes_alta                      int64
dia_alta                      int64
hora_alta                     int64
sexo                         object
edad                          int64
estado_civil                 object
ocupacion                    object
escolaridad                  object
estado                       object
municipio                    object
colonia                      object
cp                           object
plataforma                   object
servicio                     object
razon_llamada_gral           object
razon_llamada_especifica     object
llamada_detalles             object
dtype: object

###**Modificación del dataframe limpio y renombrado.** 

Es conveniente modificar los valores del dataframe al tipo de formato correspondiente como es el caso de fecha_alta y folio (únicamente contiene valores enteros).Además en este caso, y debido al formato en el que está la columna hora_alta no será útil para el análisis por lo que la eliminaremos.  

In [ ]:
#Cambiando el formato de fecha_alta de string a datetime
df_llamadas_cdmx_limpio_renombrado['fecha_alta'] = pd.to_datetime(df_llamadas_cdmx_limpio_renombrado['fecha_alta'])
df_llamadas_cdmx_limpio_renombrado.head(2)

folio  ...          llamada_detalles
0  3012.0  ...  referencia institucional
1  3013.0  ...              abuso sexual

[2 rows x 20 columns]

In [ ]:
df_llamadas_cdmx_limpio_renombrado.dtypes
print(df_llamadas_cdmx_limpio_renombrado.columns)

Index(['folio', 'fecha_alta', 'año_alta', 'mes_alta', 'dia_alta', 'hora_alta',
       'sexo', 'edad', 'estado_civil', 'ocupacion', 'escolaridad', 'estado',
       'municipio', 'colonia', 'cp', 'plataforma', 'servicio',
       'razon_llamada_gral', 'razon_llamada_especifica', 'llamada_detalles'],
      dtype='object')


In [ ]:
#Cambiamos el formato de folio de float64 a int64
df_llamadas_cdmx_limpio_renombrado['folio'] = df_llamadas_cdmx_limpio_renombrado['folio'].astype(int)

In [ ]:
df_llamadas_cdmx_limpio_renombrado.dtypes

folio                                int64
fecha_alta                  datetime64[ns]
año_alta                             int64
mes_alta                             int64
dia_alta                             int64
hora_alta                            int64
sexo                                object
edad                                 int64
estado_civil                        object
ocupacion                           object
escolaridad                         object
estado                              object
municipio                           object
colonia                             object
cp                                  object
plataforma                          object
servicio                            object
razon_llamada_gral                  object
razon_llamada_especifica            object
llamada_detalles                    object
dtype: object

In [ ]:
# Eliminamos la columna de hora_alta
df_llamadas_cdmx_final = df_llamadas_cdmx_limpio_renombrado.drop(['hora_alta'],axis=1)
df_llamadas_cdmx_final.head(3)

folio  ...          llamada_detalles
0   3012  ...  referencia institucional
1   3013  ...              abuso sexual
2   3014  ...        violencia familiar

[3 rows x 19 columns]

### **Filtrado de la información relevante**
Como las llamadas fueron realizadas con diversos fines, es necesario filtrar los datos de aquellas que son relevantes para el tema de violencia contra la mujer. Para ello utilizaremos las columnas **razon_llamada_gral** , **razon_llamada_especifica** y **llamada_detalles**. 

In [ ]:
#El tamaño del dataframe es ahora
df_llamadas_cdmx_final.shape

(624850, 19)

In [ ]:
# Valores que toma la columna 'razon_llamada_gral'
print(df_llamadas_cdmx_final['razon_llamada_gral'].unique())

['informacion general' 'penal' 'laboral' 'familiar' 'administrativa'
 'arrendamiento' 'mercantil' 'civil' 'seguridad social' 'fiscal'
 'instituciones' 'ortopedia y traumatologia' 'medicamentos'
 'signos y sintomas generales' 'cirugia' 'cardiologia' 'adicciones'
 'ginecologia obstetricia' 'toxicologia' 'conflictos emocionales'
 'noviazgo' 'gastroenterologia' 'otorrinolaringologia' 'odontologia'
 'sexualidad' 'pareja' 'violencia' 'familia' 'infectologia'
 'examenes de laboratorio' 'psiquiatria' 'notarial'
 'salud sexual y reproductiva' 'endocrinologias' 'medicina preventiva'
 'neurologia' 'oftalmologia' 'dermatologia' 'neumologia' 'alergologia'
 'urologia' 'circulatorio' 'nutricion' 'hematologia' 'salud'
 'servicios del área' 'escolar' 'oncologia' 'grupo de pares'
 'reumatologia' 'neonatologia' 'material medico' 'enfermeades endemicas'
 'donacion de organos' 'hipertension' 'enfermedades mas comunes'
 'traumatismo' 'convulsiones' 'intoxicación o envenenamiento' 'diabetes'
 'maniobras' 'ah

In [ ]:
#Realizamos un primer filrado utilizando razon_llamada_gral con los temas penal, pareja y noviazgo. 
df_llamadas_cdmx_filtrado_gral = df_llamadas_cdmx_final[df_llamadas_cdmx_final.razon_llamada_gral.str.contains('penal|pareja|noviazgo')]

In [ ]:
#Nos damos cuenta que aún tenemos registros relacionados con otros temas como "delitos conta el patrimonio" que debemos filtrar
df_llamadas_cdmx_filtrado_gral 

folio  ...     llamada_detalles
1         3013  ...         abuso sexual
2         3014  ...   violencia familiar
6         3022  ...   violencia familiar
8         3024  ...   abuso de confianza
10        3029  ...             lesiones
...        ...  ...                  ...
624831  871713  ...  daño a la propiedad
624834  871716  ...    enfrentar ruptura
624836  871718  ...   violencia familiar
624837  871719  ...             lesiones
624846  871728  ...   violencia familiar

[98343 rows x 19 columns]

In [ ]:
#Mantenemos todos los registros resultantes al razon_llamada_gral = 'violencia' 
df_llamadas_cdmx_filtrado_violencia = df_llamadas_cdmx_final[df_llamadas_cdmx_final.razon_llamada_gral.str.contains('violencia')]

In [ ]:
#Tamaño del dataframe
df_llamadas_cdmx_filtrado_violencia.shape

(25231, 19)

In [ ]:
# Realizamos el segundo filtrado de llamadas generales para delimitarlo a la violencia física y del hogar mediante palabras clave
# Obtenemos el dataframe filtrado general que solamente incluye llamadas relacionadas con violencia  
df_llamadas_cdmx_filtrado_gral = df_llamadas_cdmx_filtrado_gral[df_llamadas_cdmx_filtrado_gral.razon_llamada_especifica.str.contains('integridad | libertad | seguridad | violencia')]

In [ ]:
df_llamadas_cdmx_filtrado_gral.shape

(40503, 19)

In [ ]:
# Para tener el dataframe conpleto es necesario unir los dataframes de  df_llamadas_cdmx_filtrado_gral y df_llamadas_cdmx_filtrado_violencia
# ¡Listo! Tenemos el dataframe que vamos a utilizar para analizar 
df_llamadas_violencia_cdmx = pd.concat([df_llamadas_cdmx_filtrado_gral, df_llamadas_cdmx_filtrado_violencia], axis=0)
df_llamadas_violencia_cdmx.tail(3)

folio  ...                 llamada_detalles
624832  871714  ...  solicitud de servicios de apoyo
624842  871724  ...                         familiar
624843  871725  ...  solicitud de servicios de apoyo

[3 rows x 19 columns]

In [ ]:
#El tamaño de este dataframe es 
df_llamadas_violencia_cdmx.shape

(65734, 19)

### **Analisis Exploratorio de datos.**
Ya tenemos la base de datos limpia y con las columnas deseadas, por lo que es momento de obtener un análisis estadístico y realizar agrupaciones. 

In [ ]:
#Agrupando los datos de acuerdo al sexo de la persona que realizó la llamada y contando el número de llamadas. 
#Con el fin de observar los porcentajes de mujeres y hombres que realizaron la llamada con tema de violencia. 

df_llamadas_violencia_cdmx.groupby(['sexo']).size() #Es notorio que el mayor porcentaje lo representan las mujeres 

sexo
femenino     51582
masculino    14152
dtype: int64

In [ ]:
df_llamadas_violencia_cdmx.edad.describe() #La columna numérica de la cual podemos obtener más datos es edad 

count    65734.000000
mean        41.462896
std         13.128671
min          2.000000
25%         32.000000
50%         40.000000
75%         50.000000
max         99.000000
Name: edad, dtype: float64

In [ ]:
# Agrupamos los datos estadísticos de promedio, desviación estándar, máximo, mínimo y los cuantiles de acuerdo a la edad.
estadistica_edad = df_llamadas_violencia_cdmx.groupby(['sexo']).edad.describe()

In [ ]:
#Eliminamos la columna count ya que anteriormente ya obtuvimos dicha información con .size()
estadistica_edad = estadistica_edad.drop(['count'],axis=1)
estadistica_edad

mean        std  min   25%   50%   75%   max
sexo                                                        
femenino   41.477453  13.131449  3.0  32.0  40.0  50.0  96.0
masculino  41.409836  13.118866  2.0  32.0  40.0  50.0  99.0

De lo anterior observamos que el promedio de edad de las personas que realizaron las llamadas es ***41 años*** para ambos sexos, con una desviación estándar de ***13 años*** y con los cuantiles observamos los rangos de edades en las que caen el 25%,50% y 75% de los datos.

In [ ]:
df_razon_llamada_gral_por_sexo = df_llamadas_violencia_cdmx.groupby(['sexo','razon_llamada_gral'])[["folio"]].agg("count")
df_razon_llamada_gral_por_sexo.columns = ["conteo_llamada"]
df_razon_llamada_gral_por_sexo

conteo_llamada
sexo      razon_llamada_gral                
femenino  penal                        29781
          violencia                    21801
masculino penal                        10722
          violencia                     3430

In [ ]:
razon_especifica_llamada = df_llamadas_violencia_cdmx.groupby(['sexo','razon_llamada_especifica']).size()
razon_especifica_llamada

sexo       razon_llamada_especifica                                                             
femenino   de género                                                                                15039
           delitos contra la integridad familiar                                                    16270
           delitos contra la libertad personal                                                       1977
           delitos contra la libertad y la seguridad sexuales y el normal desarrollo psicosexual     2988
           delitos contra la paz, la seguridad de las personas y la inviolabilidad del domicilio     4447
           delitos contra la seguridad colectiva                                                       22
           delitos contra la seguridad de la subsistencia familiar                                    444
           delitos contra la seguridad de las instituciones del distrito federal                        5
           delitos contra la vida y la integridad corpo

In [ ]:
df_llamadas_2016_2021_por_sexo = df_llamadas_violencia_cdmx.groupby([df_llamadas_violencia_cdmx['fecha_alta'].dt.year,'sexo'])[["folio"]].agg("count")
#renombro a la agrupación como conteo_llamadas:
df_llamadas_2016_2021_por_sexo.columns = ["conteo_llamadas"]
df_llamadas_2016_2021_por_sexo

conteo_llamadas
fecha_alta sexo                      
2016       femenino               645
           masculino              234
2017       femenino              3525
           masculino             1141
2018       femenino              8142
           masculino             2657
2019       femenino             11408
           masculino             4025
2020       femenino             24500
           masculino             5356
2021       femenino              3362
           masculino              739

#### **Llamadas realizadas por mujeres en temas de violencia.** 

In [ ]:
df_llamadas_mujeres_violencia =  df_llamadas_violencia_cdmx[df_llamadas_violencia_cdmx.sexo.str.contains('femenino')]

In [ ]:
llamadas_mujeres_razon_especifica = df_llamadas_mujeres_violencia.groupby(['razon_llamada_especifica']).size().sort_values(ascending= False)
llamadas_mujeres_razon_especifica 

razon_llamada_especifica
delitos contra la integridad familiar                                                    16270
de género                                                                                15039
delitos contra la paz, la seguridad de las personas y la inviolabilidad del domicilio     4447
otra                                                                                      3823
delitos contra la vida y la integridad corporal                                           3628
delitos contra la libertad y la seguridad sexuales y el normal desarrollo psicosexual     2988
infantil                                                                                  2819
delitos contra la libertad personal                                                       1977
delitos contra la seguridad de la subsistencia familiar                                    444
discriminación                                                                             120
delitos contra la segurid

In [ ]:
df_llamadas_mujeres_violencia.groupby(['edad']).size().sort_values(ascending= False)

edad
45    2683
40    2221
35    2191
50    1653
30    1621
      ... 
91       3
93       2
5        1
4        1
96       1
Length: 91, dtype: int64

#### **Análisis de los datos respecto a la situación social: estado_civil 	ocupacion y	escolaridad.**

In [ ]:
#Escolaridad 
df_llamadas_escolaridad = df_llamadas_violencia_cdmx.groupby(['sexo','escolaridad'])[['folio']].agg("count")
df_llamadas_escolaridad.columns = ["conteo_llamadas"]
print(df_llamadas_escolaridad)

#Ocupación
df_llamadas_ocupacion = df_llamadas_violencia_cdmx.groupby(['sexo','ocupacion'])[['folio']].agg("count")
df_llamadas_ocupacion.columns = ["conteo_llamadas"]
print(df_llamadas_ocupacion)

#Estado Civil
df_llamadas_estado_civil = df_llamadas_violencia_cdmx.groupby(['sexo','estado_civil'])[['folio']].agg("count")
df_llamadas_estado_civil.columns = ["conteo_llamadas"]
print(df_llamadas_estado_civil)

                           conteo_llamadas
sexo      escolaridad                     
femenino  bachillerato               20927
          doctorado                    108
          licenciatura                9026
          maestria                     723
          primaria                    3951
          secundaria                 16043
          sin escolaridad              804
masculino bachillerato                5703
          doctorado                     44
          licenciatura                2855
          maestria                     206
          primaria                    1015
          secundaria                  4143
          sin escolaridad              186
                                          conteo_llamadas
sexo      ocupacion                                      
femenino  comerciante                                3327
          desempleado (a)                            2204
          empleada del hogar(remunerado)              648
          empleado (a)

In [ ]:
#Se muestra el estado civil de las mujeres que realizaron las llamadas así como ocupación y escolaridad. Nota: no se visualizan todos ya que es
#la misma información que arriba.
df_llamadas_mujeres_estado_civil =  df_llamadas_estado_civil.loc["femenino"]
df_llamadas_mujeres_estado_civil.sort_values(by="conteo_llamadas",ascending =False)

df_llamadas_mujeres_ocupacion =  df_llamadas_ocupacion.loc["femenino"]
df_llamadas_mujeres_ocupacion.sort_values(by="conteo_llamadas",ascending =False)

df_llamadas_mujeres_escolaridad =  df_llamadas_escolaridad.loc["femenino"]
df_llamadas_mujeres_escolaridad.sort_values(by="conteo_llamadas",ascending =False)

conteo_llamadas
escolaridad                     
bachillerato               20927
secundaria                 16043
licenciatura                9026
primaria                    3951
sin escolaridad              804
maestria                     723
doctorado                    108

**¿Cómo se ha reflejado la violencia de género en los últimos años?**<br>
Durante la pandemia el número de llamadas por violencia llegó a su máximo con 24,500 llamadas en 2020, las razones de la llamada más frecuentes fueron: delitos contra la integridad familiar, violencia de género y contra la paz y seguridad.

**¿Cómo se relaciona la situación social con la violencia de género?**<br>
La escolaridad de las mujeres que realizaron las llamadas era : bachillerato 40.6% , secundaria 31% y 17.5% licenciatura. Sus ocupaciones: empleada 42.7% , ama de casa 34.2%  y comerciante 6.4%:
El de las víctimas eran solteras 56.2% , casadas 30.5% y en unión libre 12.2%.




---



### **Limpieza y análisis de `carpetas_investigacion_cdmx_2016_2020.csv `**

Esta base de datos contiene la información actualizada de las carpetas de investigación de la Fiscalía General de Justicia (FGJ) de la Ciudad de México a partir de enero de 2016.

Las variables que contiene esta base son Carpetas de investigación de delitos a nivel de calle de la FGJ por Fiscalía, Agencia, Unidad de Investigación, fecha de apertura de la carpeta de investigación, delito, categoría de delito, calle, colonia, alcaldía, coordenadas, mes y año. Esta información se actualiza mensualmente.

In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np 

In [ ]:
#Lectura de .csv
path_carpetas_investigacion = "/content/drive/MyDrive/BEDU/Fase 2/Módulo 2 - Python/Datasets/carpetas_investigacion_cdmx_2016_2020.csv"
df_carpetas_investigacion_cdmx_16_20 = pd.read_csv(path_carpetas_investigacion,encoding="utf-8")
df_carpetas_investigacion_cdmx_16_20.head(3)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


ao_hechos mes_hechos         fecha_hechos  ...  competencia   longitud    latitud
0     2016.0      Enero  2016-01-31 22:16:00  ...          NaN -99.140215  19.380315
1     2016.0      Enero  2016-01-31 20:50:00  ...          NaN -99.108403  19.352859
2     2016.0    Febrero  2016-02-01 00:30:00  ...          NaN -99.061321  19.356451

[3 rows x 18 columns]

In [ ]:
#Obtenemos el número de registros y columnas que hay en el dataframe
df_carpetas_investigacion_cdmx_16_20.shape

(1151850, 18)

In [ ]:
#Obtenemos el nombre de las columnas
df_carpetas_investigacion_cdmx_16_20.columns

Index(['ao_hechos', 'mes_hechos', 'fecha_hechos', 'ao_inicio', 'mes_inicio',
       'fecha_inicio', 'delito', 'fiscalia', 'agencia', 'unidad_investigacion',
       'categoria_delito', 'calle_hechos', 'calle_hechos2', 'colonia_hechos',
       'alcaldia_hechos', 'competencia', 'longitud', 'latitud'],
      dtype='object')

In [ ]:
#Creamos un diccionario con los nuevos nombres de las columnas
nuevas_columnas = {
    'ao_hechos' : 'anio_hechos',
    'ao_inicio' : 'anio_inicio',
    'calle_hechos2' : 'calle_hechos_2'
}

#Cambiamos el nombre de las columnas
df_carpetas_investigacion_cdmx_16_20 = df_carpetas_investigacion_cdmx_16_20.rename(columns=nuevas_columnas)
df_carpetas_investigacion_cdmx_16_20.head(2)

anio_hechos mes_hechos  ...   longitud    latitud
0       2016.0      Enero  ... -99.140215  19.380315
1       2016.0      Enero  ... -99.108403  19.352859

[2 rows x 18 columns]

Analizamos los tipos de datos y observamos que:
- 

`fecha_hechos` y `fecha_inicio` necesitan cambiar el tipo de dato a *datetime*
- `anio_hechos` debe cambiar a *int* porque son números cerrados correspondientes a los años 2016-2021

Sin embargo es necesario observar si existen NaNs en el DataFrame para que no arroje un error a la hora de cambiar el tipo de dato. 

In [ ]:
#Analizamos tipo de datos
df_carpetas_investigacion_cdmx_16_20.dtypes

anio_hechos             float64
mes_hechos               object
fecha_hechos             object
anio_inicio               int64
mes_inicio               object
fecha_inicio             object
delito                   object
fiscalia                 object
agencia                  object
unidad_investigacion     object
categoria_delito         object
calle_hechos             object
calle_hechos_2           object
colonia_hechos           object
alcaldia_hechos          object
competencia              object
longitud                float64
latitud                 float64
dtype: object

In [ ]:
#Antes de cambiar los tipos de datos
#contamos el numero de valores NaN que tenemos
df_carpetas_investigacion_cdmx_16_20.isna().sum(axis=0)

anio_hechos                433
mes_hechos                 433
fecha_hechos               433
anio_inicio                  0
mes_inicio                   0
fecha_inicio                 0
delito                       0
fiscalia                     2
agencia                      0
unidad_investigacion       227
categoria_delito             0
calle_hechos              2947
calle_hechos_2          698673
colonia_hechos           46786
alcaldia_hechos           3146
competencia             931933
longitud                 45819
latitud                  45818
dtype: int64

In [ ]:
#Vemos que tenemos la mayor cantidad de NaNs en las columnas competencia, y calle_hechos_2.

#Obteniendo indices
index = df_carpetas_investigacion_cdmx_16_20['anio_hechos'].index[df_carpetas_investigacion_cdmx_16_20['anio_hechos'].apply(np.isnan)]
#accesando a ellos
df_carpetas_investigacion_cdmx_16_20.loc[index].head(5)

#Explorando los datos, notamos que no falta ningún dato importante sobre el inicio de la carpeta.
#Se tienen algunos valores faltantes sobre cúando y dónde ocurrieron los hechos del delito pero pueden mantenerse.


anio_hechos mes_hechos fecha_hechos  ...  competencia   longitud    latitud
628           NaN        NaN          NaN  ...          NaN -99.009777  19.362143
784           NaN        NaN          NaN  ...          NaN -99.110716  19.373883
2160          NaN        NaN          NaN  ...          NaN        NaN        NaN
2227          NaN        NaN          NaN  ...          NaN        NaN        NaN
2815          NaN        NaN          NaN  ...          NaN -99.067324  19.472209

[5 rows x 18 columns]

In [ ]:
#Modificamos el formato de las columnas mes
df_carpetas_investigacion_cdmx_16_20['mes_inicio'] = df_carpetas_investigacion_cdmx_16_20['mes_inicio'].str.upper()
df_carpetas_investigacion_cdmx_16_20['mes_hechos'] = df_carpetas_investigacion_cdmx_16_20['mes_hechos'].str.upper()


In [ ]:
#Eliminamos las columnas competencia y calle_hechos_2 por la gran cantidad de NaNs que contienen
df_carpetas_investigacion_cdmx_16_20 = df_carpetas_investigacion_cdmx_16_20.drop(labels=['competencia','calle_hechos_2'], axis=1)

In [ ]:
#Rellenamos los valores NaNs para recuperar la información

df_carpetas_investigacion_cdmx_16_20['anio_hechos'] = df_carpetas_investigacion_cdmx_16_20['anio_hechos'].fillna(0)
df_carpetas_investigacion_cdmx_16_20['mes_hechos'] = df_carpetas_investigacion_cdmx_16_20['mes_hechos'].fillna('NO ESPECIFICADO')
df_carpetas_investigacion_cdmx_16_20['fecha_hechos'] = df_carpetas_investigacion_cdmx_16_20['fecha_hechos'].fillna(0)

df_carpetas_investigacion_cdmx_16_20['fiscalia'] = df_carpetas_investigacion_cdmx_16_20['fiscalia'].fillna('NO ESPECIFICADO')
df_carpetas_investigacion_cdmx_16_20['unidad_investigacion'] = df_carpetas_investigacion_cdmx_16_20['unidad_investigacion'].fillna('NO ESPECIFICADO')
df_carpetas_investigacion_cdmx_16_20['calle_hechos'] = df_carpetas_investigacion_cdmx_16_20['calle_hechos'].fillna('NO ESPECIFICADO')
df_carpetas_investigacion_cdmx_16_20['colonia_hechos'] = df_carpetas_investigacion_cdmx_16_20['colonia_hechos'].fillna('NO ESPECIFICADO')
df_carpetas_investigacion_cdmx_16_20['alcaldia_hechos'] = df_carpetas_investigacion_cdmx_16_20['alcaldia_hechos'].fillna('NO ESPECIFICADO')

df_carpetas_investigacion_cdmx_16_20['longitud'] = df_carpetas_investigacion_cdmx_16_20['longitud'].fillna(0)
df_carpetas_investigacion_cdmx_16_20['latitud'] = df_carpetas_investigacion_cdmx_16_20['latitud'].fillna(0)

#Confirmamos que ya no tenemos NaNs
df_carpetas_investigacion_cdmx_16_20.isna().sum(axis=0)

anio_hechos             0
mes_hechos              0
fecha_hechos            0
anio_inicio             0
mes_inicio              0
fecha_inicio            0
delito                  0
fiscalia                0
agencia                 0
unidad_investigacion    0
categoria_delito        0
calle_hechos            0
colonia_hechos          0
alcaldia_hechos         0
longitud                0
latitud                 0
dtype: int64

In [ ]:
#Ya limpios los datos, cambiamos el tipo de dato de las columnas
df_carpetas_investigacion_cdmx_16_20['fecha_hechos'] = pd.to_datetime(df_carpetas_investigacion_cdmx_16_20['fecha_hechos'], errors = 'coerce')
df_carpetas_investigacion_cdmx_16_20['fecha_inicio'] = pd.to_datetime(df_carpetas_investigacion_cdmx_16_20['fecha_inicio'], errors = 'coerce')
df_carpetas_investigacion_cdmx_16_20['anio_hechos'] = df_carpetas_investigacion_cdmx_16_20['anio_hechos'].astype('int64')

#Confirmamos el cambio de tipo de dato
df_carpetas_investigacion_cdmx_16_20.dtypes

anio_hechos                      int64
mes_hechos                      object
fecha_hechos            datetime64[ns]
anio_inicio                      int64
mes_inicio                      object
fecha_inicio            datetime64[ns]
delito                          object
fiscalia                        object
agencia                         object
unidad_investigacion            object
categoria_delito                object
calle_hechos                    object
colonia_hechos                  object
alcaldia_hechos                 object
longitud                       float64
latitud                        float64
dtype: object

In [ ]:
#Ya que tenemos todo en orden podemos empezar a hacer agrupaciones

#Delitos totales reportados por año en el que ocurrió el delito
df_carpetas_investigacion_cdmx_16_20.groupby('anio_hechos')['delito'].count().sort_values(ascending=False).head(5)

anio_hechos
2018    253276
2019    242322
2017    226912
2016    194800
2020    194121
Name: delito, dtype: int64

In [ ]:
#Delitos totales reportados por año en el que se reportó el delito
df_carpetas_investigacion_cdmx_16_20.groupby('anio_inicio')['delito'].count().sort_values(ascending=False)

anio_inicio
2018    255311
2019    250386
2017    228323
2020    204043
2016    197913
2021     15874
Name: delito, dtype: int64

In [ ]:
#Delitos totales por año y mes en el que se reportó el delito
df_carpetas_investigacion_cdmx_16_20.groupby(['anio_inicio','mes_inicio'])[['delito']].count().sort_values(['anio_inicio','delito'], ascending=[True,False])

delito
anio_inicio mes_inicio        
2016        OCTUBRE      17901
            SEPTIEMBRE   17138
            NOVIEMBRE    17003
            ABRIL        16992
            AGOSTO       16924
...                        ...
2020        JULIO        16515
            JUNIO        13671
            ABRIL        12287
            MAYO         11371
2021        ENERO        15874

[61 rows x 1 columns]

In [ ]:
#Delitos totales registrados por alcaldía
df_carpetas_investigacion_cdmx_16_20.groupby('alcaldia_hechos')['delito'].count().sort_values(ascending=False).head(6)

alcaldia_hechos
CUAUHTEMOC          180670
IZTAPALAPA          173204
GUSTAVO A MADERO    115418
BENITO JUAREZ        96603
ALVARO OBREGON       77687
COYOACAN             76735
Name: delito, dtype: int64

In [ ]:
#Delitos totales registrados, clasificados por nombre del delito
df_carpetas_investigacion_cdmx_16_20.groupby('delito')['categoria_delito'].count().sort_values(ascending=False).head(10)

delito
VIOLENCIA FAMILIAR                                       113712
FRAUDE                                                    69387
ROBO DE OBJETOS                                           68222
ROBO A NEGOCIO SIN VIOLENCIA                              65024
AMENAZAS                                                  60043
ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA            58299
DENUNCIA DE HECHOS                                        40150
ROBO DE ACCESORIOS DE AUTO                                36141
ROBO DE OBJETOS DEL INTERIOR DE UN VEHICULO               31897
ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VIOLENCIA     30508
Name: categoria_delito, dtype: int64

In [ ]:
#Tendencia por delegación de cualquier tipo de violencia de género desde 2016-2021

lista_violencia = ['VIOLENCIA FAMILIAR', 'ABUSO SEXUAL', 'VIOLACION', 'ACOSO SEXUAL',
                         'VIOLACION EQUIPARADA', 'CONTRA LA INTIMIDAD SEXUAL', 'ABORTO', 'TRATA DE PERSONAS', 'PORNOGRAFÍA',
                         'FEMINICIDIO', 'VIOLACION DE CORRESPONDENCIA','VIOLACION TUMULTUARIA','ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES',
                         'VIOLACION EQUIPARADA POR CONOCIDO', 'TENTATIVA DE VIOLACION', 'FEMINICIDIO POR ARMA BLANCA', 
                         'FEMINICIDIO POR DISPARO DE ARMA DE FUEGO', 'PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)', 
                         'FEMINICIDIO POR GOLPES', 'TENTATIVA DE FEMINICIDIO', 'VIOLACION EQUIPARADA Y ROBO DE VEHICULO', 'LENOCINIO', 
                         'VIOLACION TUMULTUARIA EQUIPARADA POR CONOCIDO', 'VIOLACION TUMULTUARIA EQUIPARADA' ,'INCESTO', 'VIOLACION Y ROBO DE VEHICULO',
                         'PROCREACION ASISTIDA, INSEMINACION ARTIFICIAL Y ESTERILIZACION FORZADA', 'PROCREACION ASISTIDA']

df_carpetas_investigacion_cdmx_16_20[df_carpetas_investigacion_cdmx_16_20['delito'].isin(lista_violencia)].groupby(['alcaldia_hechos'])['delito'].count().sort_values(ascending=False).head(16)

alcaldia_hechos
IZTAPALAPA                24712
GUSTAVO A MADERO          15927
CUAUHTEMOC                13427
ALVARO OBREGON            10336
TLALPAN                    9849
COYOACAN                   8954
VENUSTIANO CARRANZA        7822
IZTACALCO                  7663
XOCHIMILCO                 6769
AZCAPOTZALCO               6192
TLAHUAC                    5643
BENITO JUAREZ              5405
MIGUEL HIDALGO             5323
LA MAGDALENA CONTRERAS     4611
CUAJIMALPA DE MORELOS      2473
MILPA ALTA                 2081
Name: delito, dtype: int64

In [ ]:
#Creación de subdataframe sobre los delitos relacionados con violencia de género
#Ordenado por año, alcaldía y tipo de delito 

df_violencia_de_genero_cdmx_16_20 = pd.DataFrame(df_carpetas_investigacion_cdmx_16_20[df_carpetas_investigacion_cdmx_16_20['delito'].isin(lista_violencia)].groupby(['anio_inicio','alcaldia_hechos','delito']).count())
df_violencia_de_genero_cdmx_16_20_ordenado = pd.DataFrame(df_violencia_de_genero_cdmx_16_20['fiscalia'].sort_values(ascending=False))
df_violencia_de_genero_cdmx_16_20_ordenado = df_violencia_de_genero_cdmx_16_20_ordenado.rename(columns={'fiscalia':'total_delitos'})
df_violencia_de_genero_cdmx_16_20_ordenado.head(6)

total_delitos
anio_inicio alcaldia_hechos  delito                           
2020        IZTAPALAPA       VIOLENCIA FAMILIAR           4723
2019        IZTAPALAPA       VIOLENCIA FAMILIAR           4636
2016        IZTAPALAPA       VIOLENCIA FAMILIAR           3981
2020        GUSTAVO A MADERO VIOLENCIA FAMILIAR           3709
2017        IZTAPALAPA       VIOLENCIA FAMILIAR           3690
2018        IZTAPALAPA       VIOLENCIA FAMILIAR           3361

In [ ]:
#Delito más recuurrente en el 2020 dividido por alcaldia
df_violencia_de_genero_cdmx_16_20_ordenado.filter(like='2020', axis=0).head(16)

total_delitos
anio_inicio alcaldia_hechos        delito                           
2020        IZTAPALAPA             VIOLENCIA FAMILIAR           4723
            GUSTAVO A MADERO       VIOLENCIA FAMILIAR           3709
            ALVARO OBREGON         VIOLENCIA FAMILIAR           2173
            CUAUHTEMOC             VIOLENCIA FAMILIAR           2157
            TLALPAN                VIOLENCIA FAMILIAR           1860
            COYOACAN               VIOLENCIA FAMILIAR           1793
            VENUSTIANO CARRANZA    VIOLENCIA FAMILIAR           1551
            IZTACALCO              VIOLENCIA FAMILIAR           1509
            XOCHIMILCO             VIOLENCIA FAMILIAR           1497
            AZCAPOTZALCO           VIOLENCIA FAMILIAR           1442
            TLAHUAC                VIOLENCIA FAMILIAR           1268
            MIGUEL HIDALGO         VIOLENCIA FAMILIAR           1167
            LA MAGDALENA CONTRERAS VIOLENCIA FAMILIAR           1078
            BENITO JUAREZ          VIOLENCIA FAMILIAR            862
            IZTAPALAPA             ABUSO SEXUAL                  520
            CUAJIMALPA DE MORELOS  VIOLENCIA FAMILIAR            512

### **Limpieza y análisis de `victimas_carpeta_cdmx_2016_2020.csv `**
 
Esta base de datos contiene la información actualizada de las víctimas de los delitos en las carpetas de investigación de la Fiscalía General de Justicia (FGJ) de la Ciudad de México a partir de enero de 2019.

Incluye variables como sexo, edad, fecha, hora, denunciante. En el caso del denunciante, es importante aclarar que el denunciante no siempre es la víctima.

Los datos fueron actualizados el 29 de julio de 2020. 

In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np

In [ ]:
#Lectura de .csv
path_victimas_carpetas = "/content/drive/MyDrive/BEDU/Fase 2/Módulo 2 - Python/Datasets/victimas_carpeta_cdmx_2019_2020.csv"
df_victimas_carpeta_cdmx_19_20 = pd.read_csv(path_victimas_carpetas,index_col=0,encoding="utf-8")
df_victimas_carpeta_cdmx_19_20.head(3)


Año_inicio Mes_inicio FechaInicio  ... Calle_hechos2   latitud  longitud
idCarpeta                                     ...                                  
8324429          2019      Enero  04/01/2019  ...           NaN  19.36125 -99.18314
8324430          2019      Enero  04/01/2019  ...           NaN  19.47181 -99.16458
8324431          2019      Enero  04/01/2019  ...           NaN  19.33797 -99.18611

[3 rows x 21 columns]

In [ ]:
#Obtenemos el número de registros y columnas que hay en el dataframe
df_victimas_carpeta_cdmx_19_20.shape

(496863, 21)

In [ ]:
#Obtenemos el nombre de las columnas
df_victimas_carpeta_cdmx_19_20.columns

Index(['Año_inicio', 'Mes_inicio', 'FechaInicio', 'Delito', 'Categoria',
       'Sexo', 'Edad', 'TipoPersona', 'CalidadJuridica', 'competencia',
       'Año_hecho', 'Mes_hecho', 'FechaHecho', 'HoraHecho', 'HoraInicio',
       'AlcaldiaHechos', 'ColoniaHechos', 'Calle_hechos', 'Calle_hechos2',
       'latitud', 'longitud'],
      dtype='object')

In [ ]:
#Creamos un diccionario con los nuevos nombres de las columnas
nuevas_columnas = {
    'idCarpeta': 'id_carpeta',
    'Año_inicio' : 'anio_inicio',
    'Mes_inicio' : 'mes_inicio',
    'FechaInicio' : 'fecha_inicio',
    'Delito' : 'delito',
    'Categoria': 'categoria_delito',
    'Sexo' : 'sexo',
    'Edad' : 'edad',
    'TipoPersona' : 'tipo_persona',
    'CalidadJuridica': 'calidad_juridica',
    #'competencia'
    'Año_hecho': 'anio_hechos',
    'Mes_hecho' : 'mes_hechos',
    'FechaHecho' : 'fecha_hechos',
    'HoraHecho' : 'hora_hechos',
    'HoraInicio' : 'hora_inicio',
    'AlcaldiaHechos':'alcaldia_hechos',
    'ColoniaHechos' : 'colonia_hechos',
    'Calle_hechos' : 'calle_hechos',
    'Calle_hechos2' : 'calle_hechos_2'
    #latitud
    #longitud
}

#Cambiamos el nombre de las columnas
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20.rename(columns=nuevas_columnas)
df_victimas_carpeta_cdmx_19_20.head(2)

anio_inicio mes_inicio  ...   latitud  longitud
idCarpeta                          ...                    
8324429           2019      Enero  ...  19.36125 -99.18314
8324430           2019      Enero  ...  19.47181 -99.16458

[2 rows x 21 columns]

In [ ]:
#Analizamos tipo de datos y observamos que se requiere cambiar algunos
df_victimas_carpeta_cdmx_19_20.dtypes


anio_inicio           int64
mes_inicio           object
fecha_inicio         object
delito               object
categoria_delito     object
sexo                 object
edad                float64
tipo_persona         object
calidad_juridica     object
competencia          object
anio_hechos         float64
mes_hechos           object
fecha_hechos         object
hora_hechos          object
hora_inicio          object
alcaldia_hechos      object
colonia_hechos       object
calle_hechos         object
calle_hechos_2       object
latitud             float64
longitud            float64
dtype: object

In [ ]:
#Antes de cambiar los tipos de datos
#contamos el numero de valores NaN que tenemos
df_victimas_carpeta_cdmx_19_20.isna().sum(axis=0)

anio_inicio              0
mes_inicio               0
fecha_inicio             0
delito                   0
categoria_delito         0
sexo                101904
edad                184752
tipo_persona          8626
calidad_juridica         0
competencia              0
anio_hechos            286
mes_hechos             286
fecha_hechos           286
hora_hechos            284
hora_inicio              1
alcaldia_hechos         64
colonia_hechos       19623
calle_hechos           942
calle_hechos_2      314899
latitud              19393
longitud             19395
dtype: int64

In [ ]:
#Vemos que tenemos la mayor cantidad de NaNs en las columnas calle_hechos_2.

#Obteniendo indices
index = df_victimas_carpeta_cdmx_19_20['edad'].index[df_victimas_carpeta_cdmx_19_20['edad'].apply(np.isnan)]
#accesando a ellos
df_victimas_carpeta_cdmx_19_20.loc[index].head(3)

#Explorando los datos, notamos que no falta ningún dato importante sobre el inicio de la carpeta a excepción de un valor referente a la hora
#sin embargo, falta información sobre sexo y edad de un gran número de víctimas.


anio_inicio mes_inicio  ...   latitud  longitud
idCarpeta                          ...                    
8324438           2019      Enero  ...  19.35480 -99.06324
8324438           2019      Enero  ...  19.35480 -99.06324
8324482           2019      Enero  ...  19.44962 -99.12782

[3 rows x 21 columns]

In [ ]:
#Modificamos el formato de las columnas mes y sexo
df_victimas_carpeta_cdmx_19_20['mes_inicio'] = df_victimas_carpeta_cdmx_19_20['mes_inicio'].str.upper()
df_victimas_carpeta_cdmx_19_20['mes_hechos'] = df_victimas_carpeta_cdmx_19_20['mes_hechos'].str.upper()
df_victimas_carpeta_cdmx_19_20['sexo'] = df_victimas_carpeta_cdmx_19_20['sexo'].str.upper()


In [ ]:
#Eliminamos las columnas competencia y calle_hechos_2 por la gran cantidad de NaNs que contienen
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20.drop(labels=['calle_hechos_2'], axis=1)

In [ ]:
#Combinaremos las columnas fecha_inicio y hora_inicio, modificando la columna de fecha_inicio
#despues le cambiamos el tipo de dato a datetime
df_victimas_carpeta_cdmx_19_20['fecha_inicio'] = df_victimas_carpeta_cdmx_19_20['fecha_inicio'] + " " +df_victimas_carpeta_cdmx_19_20['hora_inicio']
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20[ ['fecha_inicio'] + [ col for col in df_victimas_carpeta_cdmx_19_20.columns if col != 'fecha_inicio' ] ]
df_victimas_carpeta_cdmx_19_20['fecha_inicio'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_inicio'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20.drop(labels=['hora_inicio'], axis=1)
df_victimas_carpeta_cdmx_19_20.head(1)

fecha_inicio  anio_inicio  ...   latitud  longitud
idCarpeta                                   ...                    
8324429   2019-04-01 12:19:00         2019  ...  19.36125 -99.18314

[1 rows x 19 columns]

In [ ]:
#Combinaremos las columnas fecha_hechos y hora_hechos, modificando la columna de fecha_hechos
#despues le cambiamos el tipo de dato a datetime
df_victimas_carpeta_cdmx_19_20['fecha_hechos'] = df_victimas_carpeta_cdmx_19_20['fecha_hechos'] + " " +df_victimas_carpeta_cdmx_19_20['hora_hechos']
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20[ ['fecha_hechos'] + [ col for col in df_victimas_carpeta_cdmx_19_20.columns if col != 'fecha_hechos' ] ]
df_victimas_carpeta_cdmx_19_20['fecha_hechos'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_hechos'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20 = df_victimas_carpeta_cdmx_19_20.drop(labels=['hora_hechos'], axis=1)
df_victimas_carpeta_cdmx_19_20.head(1)

fecha_hechos        fecha_inicio  ...   latitud  longitud
idCarpeta                                          ...                    
8324429   2018-08-29 12:00:00 2019-04-01 12:19:00  ...  19.36125 -99.18314

[1 rows x 18 columns]

In [ ]:
#Rellenamos los valores NaNs para recuperar la información

df_victimas_carpeta_cdmx_19_20['sexo'] = df_victimas_carpeta_cdmx_19_20['sexo'].fillna('NO ESPECIFICADO')
df_victimas_carpeta_cdmx_19_20['edad'] = df_victimas_carpeta_cdmx_19_20['edad'].fillna(0)
df_victimas_carpeta_cdmx_19_20['tipo_persona'] = df_victimas_carpeta_cdmx_19_20['tipo_persona'].fillna('NO ESPECIFICADO')

df_victimas_carpeta_cdmx_19_20['anio_hechos'] = df_victimas_carpeta_cdmx_19_20['anio_hechos'].fillna(0)
df_victimas_carpeta_cdmx_19_20['mes_hechos'] = df_victimas_carpeta_cdmx_19_20['mes_hechos'].fillna('NO ESPECIFICADO')
df_victimas_carpeta_cdmx_19_20['fecha_hechos'] = df_victimas_carpeta_cdmx_19_20['fecha_hechos'].fillna(0)
df_victimas_carpeta_cdmx_19_20['fecha_inicio'] = df_victimas_carpeta_cdmx_19_20['fecha_inicio'].fillna(0)
#df_victimas_carpeta_cdmx_19_20['hora_inicio'] = df_victimas_carpeta_cdmx_19_20['hora_inicio'].fillna(0)
df_victimas_carpeta_cdmx_19_20['alcaldia_hechos'] = df_victimas_carpeta_cdmx_19_20['alcaldia_hechos'].fillna('NO ESPECIFICADO')
df_victimas_carpeta_cdmx_19_20['colonia_hechos'] = df_victimas_carpeta_cdmx_19_20['colonia_hechos'].fillna('NO ESPECIFICADO')
df_victimas_carpeta_cdmx_19_20['calle_hechos'] = df_victimas_carpeta_cdmx_19_20['calle_hechos'].fillna('NO ESPECIFICADO')

df_victimas_carpeta_cdmx_19_20['longitud'] = df_victimas_carpeta_cdmx_19_20['longitud'].fillna(0)
df_victimas_carpeta_cdmx_19_20['latitud'] = df_victimas_carpeta_cdmx_19_20['latitud'].fillna(0)

#Observamos si tenemos NaNs
df_victimas_carpeta_cdmx_19_20.isna().sum(axis=0)

fecha_hechos        0
fecha_inicio        0
anio_inicio         0
mes_inicio          0
delito              0
categoria_delito    0
sexo                0
edad                0
tipo_persona        0
calidad_juridica    0
competencia         0
anio_hechos         0
mes_hechos          0
alcaldia_hechos     0
colonia_hechos      0
calle_hechos        0
latitud             0
longitud            0
dtype: int64

In [ ]:
#Ya limpios los datos, cambiamos el tipo de dato de las columnas
df_victimas_carpeta_cdmx_19_20['fecha_hechos'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_hechos'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20['fecha_inicio'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_inicio'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20['anio_hechos'] = df_victimas_carpeta_cdmx_19_20['anio_hechos'].astype('int64')
df_victimas_carpeta_cdmx_19_20['edad'] = df_victimas_carpeta_cdmx_19_20['edad'].astype('int64')

#Confirmamos el cambio de tipo de dato
df_victimas_carpeta_cdmx_19_20.dtypes

fecha_hechos        datetime64[ns]
fecha_inicio        datetime64[ns]
anio_inicio                  int64
mes_inicio                  object
delito                      object
categoria_delito            object
sexo                        object
edad                         int64
tipo_persona                object
calidad_juridica            object
competencia                 object
anio_hechos                  int64
mes_hechos                  object
alcaldia_hechos             object
colonia_hechos              object
calle_hechos                object
latitud                    float64
longitud                   float64
dtype: object

In [ ]:
#Ya limpios los datos, cambiamos el tipo de dato de las columnas
df_victimas_carpeta_cdmx_19_20['fecha_hechos'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_hechos'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20['fecha_inicio'] = pd.to_datetime(df_victimas_carpeta_cdmx_19_20['fecha_inicio'], errors = 'coerce')
df_victimas_carpeta_cdmx_19_20['anio_hechos'] = df_victimas_carpeta_cdmx_19_20['anio_hechos'].astype('int64')
df_victimas_carpeta_cdmx_19_20['edad'] = df_victimas_carpeta_cdmx_19_20['edad'].astype('int64')

#Confirmamos el cambio de tipo de dato
df_victimas_carpeta_cdmx_19_20.dtypes

fecha_hechos        datetime64[ns]
fecha_inicio        datetime64[ns]
anio_inicio                  int64
mes_inicio                  object
delito                      object
categoria_delito            object
sexo                        object
edad                         int64
tipo_persona                object
calidad_juridica            object
competencia                 object
anio_hechos                  int64
mes_hechos                  object
alcaldia_hechos             object
colonia_hechos              object
calle_hechos                object
latitud                    float64
longitud                   float64
dtype: object

In [ ]:
#Victimas totales desde 2019-2021 clasificadas por sexo
df_victimas_carpeta_cdmx_19_20.groupby('sexo')['delito'].count().sort_values(ascending=False)

sexo
MASCULINO          217968
FEMENINO           176991
NO ESPECIFICADO    101904
Name: delito, dtype: int64

In [ ]:
#Victimas totales clasificados por año, sexo y mes en el que se reportó el delito
df_victimas_carpeta_cdmx_19_20.groupby(['anio_inicio','mes_inicio','sexo'])[['delito']].count().sort_values(['anio_inicio','mes_inicio','delito'], ascending=[True,True,False])

delito
anio_inicio mes_inicio sexo                   
2019        ABRIL      MASCULINO         10412
                       FEMENINO           7869
                       NO ESPECIFICADO    4640
            AGOSTO     MASCULINO         10347
                       FEMENINO           8177
...                                        ...
2020        SEPTIEMBRE FEMENINO           6907
                       NO ESPECIFICADO    3425
2021        ENERO      MASCULINO          7248
                       FEMENINO           6150
                       NO ESPECIFICADO    3176

[75 rows x 1 columns]

In [ ]:
#Victimas registrados, clasificadas por nombre del delito. 10 Delitos con mayor número de víctimas
df_victimas_carpeta_cdmx_19_20.groupby('delito')['categoria_delito'].count().sort_values(ascending=False).head(10)

delito
VIOLENCIA FAMILIAR                                       59607
FRAUDE                                                   31363
AMENAZAS                                                 30183
ROBO A TRANSEUNTE EN VIA PUBLICA CON VIOLENCIA           24784
ROBO A NEGOCIO SIN VIOLENCIA                             24589
ROBO DE OBJETOS                                          22987
ROBO A NEGOCIO CON VIOLENCIA                             16576
ROBO DE ACCESORIOS DE AUTO                               15960
ROBO DE VEHICULO DE SERVICIO PARTICULAR SIN VIOLENCIA    12300
ROBO DE OBJETOS DEL INTERIOR DE UN VEHICULO              12219
Name: categoria_delito, dtype: int64

In [ ]:
#Tendencia por delegación de cualquier tipo de violencia de género 

lista_violencia = ['VIOLENCIA FAMILIAR', 'ABUSO SEXUAL', 'VIOLACION', 'ACOSO SEXUAL',
                         'VIOLACION EQUIPARADA', 'CONTRA LA INTIMIDAD SEXUAL', 'ABORTO', 'TRATA DE PERSONAS', 'PORNOGRAFÍA',
                         'FEMINICIDIO', 'VIOLACION DE CORRESPONDENCIA','VIOLACION TUMULTUARIA','ACOSO SEXUAL AGRAVADO EN CONTRA DE MENORES',
                         'VIOLACION EQUIPARADA POR CONOCIDO', 'TENTATIVA DE VIOLACION', 'FEMINICIDIO POR ARMA BLANCA', 
                         'FEMINICIDIO POR DISPARO DE ARMA DE FUEGO', 'PRIVACION DE LA LIBERTAD PERSONAL (REALIZAR ACTO SEXUAL)', 
                         'FEMINICIDIO POR GOLPES', 'TENTATIVA DE FEMINICIDIO', 'VIOLACION EQUIPARADA Y ROBO DE VEHICULO', 'LENOCINIO', 
                         'VIOLACION TUMULTUARIA EQUIPARADA POR CONOCIDO', 'VIOLACION TUMULTUARIA EQUIPARADA' ,'INCESTO', 'VIOLACION Y ROBO DE VEHICULO',
                         'PROCREACION ASISTIDA, INSEMINACION ARTIFICIAL Y ESTERILIZACION FORZADA', 'PROCREACION ASISTIDA']

df_victimas_carpeta_cdmx_19_20[df_victimas_carpeta_cdmx_19_20['delito'].isin(lista_violencia)].groupby(['alcaldia_hechos'])['delito'].count().sort_values(ascending=False).head(16)

alcaldia_hechos
IZTAPALAPA                12691
GUSTAVO A MADERO           9233
CUAUHTEMOC                 7408
ALVARO OBREGON             5893
TLALPAN                    4970
COYOACAN                   4639
VENUSTIANO CARRANZA        4272
IZTACALCO                  3821
XOCHIMILCO                 3561
AZCAPOTZALCO               3471
MIGUEL HIDALGO             3154
TLAHUAC                    3032
BENITO JUAREZ              2624
LA MAGDALENA CONTRERAS     2480
CUAJIMALPA DE MORELOS      1452
MILPA ALTA                 1197
Name: delito, dtype: int64

In [ ]:
#Creación de subdataframe sobre los delitos relacionados con violencia de género
#Ordenado por año, alcaldía y tipo de delito

df_victimas_violencia_de_genero_cdmx_19_21 = pd.DataFrame(df_victimas_carpeta_cdmx_19_20[df_victimas_carpeta_cdmx_19_20['delito'].isin(lista_violencia)].groupby(['anio_inicio','alcaldia_hechos','delito','sexo'])['competencia'].count()).sort_values(['anio_inicio','competencia'], ascending=[True,False])
df_victimas_violencia_de_genero_cdmx_19_21 = df_victimas_violencia_de_genero_cdmx_19_21.rename(columns={'competencia':'total_victimas'})

In [ ]:
#Número de victimas en el 2019 en las 5 alcaldias con mayor registro
df_victimas_violencia_de_genero_cdmx_19_21.filter(like='2019', axis=0).head(5)

total_victimas
anio_inicio alcaldia_hechos  delito             sexo                    
2019        IZTAPALAPA       VIOLENCIA FAMILIAR FEMENINO            3758
            GUSTAVO A MADERO VIOLENCIA FAMILIAR FEMENINO            2450
            CUAUHTEMOC       VIOLENCIA FAMILIAR FEMENINO            1693
            ALVARO OBREGON   VIOLENCIA FAMILIAR FEMENINO            1650
            TLALPAN          VIOLENCIA FAMILIAR FEMENINO            1525

In [ ]:
#Número de victimas en el 2020 en las 5 alcaldias con mayor registro
df_victimas_violencia_de_genero_cdmx_19_21.filter(like='2020', axis=0).head(5)

total_victimas
anio_inicio alcaldia_hechos  delito             sexo                    
2020        IZTAPALAPA       VIOLENCIA FAMILIAR FEMENINO            3692
            GUSTAVO A MADERO VIOLENCIA FAMILIAR FEMENINO            2915
            CUAUHTEMOC       VIOLENCIA FAMILIAR FEMENINO            1737
            ALVARO OBREGON   VIOLENCIA FAMILIAR FEMENINO            1674
            TLALPAN          VIOLENCIA FAMILIAR FEMENINO            1475

In [ ]:
#Número de victimas en el 2021 en las 5 alcaldias con mayor registro
df_victimas_violencia_de_genero_cdmx_19_21.filter(like='2021', axis=0).head(5)

total_victimas
anio_inicio alcaldia_hechos  delito             sexo                    
2021        IZTAPALAPA       VIOLENCIA FAMILIAR FEMENINO             269
            GUSTAVO A MADERO VIOLENCIA FAMILIAR FEMENINO             265
            ALVARO OBREGON   VIOLENCIA FAMILIAR FEMENINO             145
            CUAUHTEMOC       VIOLENCIA FAMILIAR FEMENINO             139
            COYOACAN         VIOLENCIA FAMILIAR FEMENINO             121

### **Limpieza y análisis de `municipal_delitos_nacional_2015_ene2021.csv `**

Esta base de datos ontiene las cifras de incidencia delictiva municipal, 2015 - enero 2021 en todo México a nivel municipal. Publicados por el Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública.

Contiene variables como entidad, municipio, numeros de delitos por mes, tipo y subtipo de delito cometido.

Se añadió una nueva columna de delitos totales por año.

In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np 

In [ ]:
#Lectura de archivos .csv
path_municipal_delitos_nacional = '/content/municipal_delitos_nacional_2015_ene2021.csv'
data_municipal_delitos_nacional = pd.read_csv(path_municipal_delitos_nacional, encoding = "latin")
data_municipal_delitos_nacional.head(2)

Año  Clave_Ent         Entidad  ...  Octubre Noviembre Diciembre
0  2015          1  Aguascalientes  ...      1.0       0.0       1.0
1  2015          1  Aguascalientes  ...      0.0       0.0       0.0

[2 rows x 21 columns]

In [ ]:
#Obtenemos el numero de registros y columnas que hay en el dataframe
data_municipal_delitos_nacional.shape

(1588776, 21)

In [ ]:
#Obtenemos el nombre de las columnas
data_municipal_delitos_nacional.columns

Index(['Año', 'Clave_Ent', 'Entidad', 'Cve. Municipio', 'Municipio',
       'Bien jurídico afectado', 'Tipo de delito', 'Subtipo de delito',
       'Modalidad', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
       'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      dtype='object')

In [ ]:
#Creamos un diccionario con los nuevos nombres de las columnas
nuevas_columnas = {
    'Año':'ano',
    'Clave_Ent':'clave_entidad',
    'Entidad':'entidad', 
    'Cve. Municipio': 'clave_municipio',
    'Municipio':'municipio',
    'Bien jurídico afectado':'bien_juridico_afectado', 
    'Tipo de delito':'tipo_de_delito', 
    'Subtipo de delito': 'subtipo_delito',
    'Modalidad': 'modalidad', 
    'Enero': 'enero',
    'Febrero':'febrero', 
    'Marzo':'marzo', 
    'Abril':'abril', 
    'Mayo':'mayo', 
    'Junio':'junio',
    'Julio':'julio', 
    'Agosto':'agosto', 
    'Septiembre':'septiembre', 
    'Octubre':'octubre', 
    'Noviembre':'noviembre', 
    'Diciembre':'diciembre'  
}

#Cambiamos el nombre de las columnas
data_municipal_delitos_nacional = data_municipal_delitos_nacional.rename(columns=nuevas_columnas)
data_municipal_delitos_nacional.head(2)

ano  clave_entidad         entidad  ...  octubre noviembre diciembre
0  2015              1  Aguascalientes  ...      1.0       0.0       1.0
1  2015              1  Aguascalientes  ...      0.0       0.0       0.0

[2 rows x 21 columns]

In [ ]:
#Analizamos los tipos de datos que tenemos por columna y observamos que los datos ya tienen el tipo correcto
#La de año se queda como entero ya que no hay necesidad de pasarlo a datetime, porque solo tenemos el año
data_municipal_delitos_nacional.dtypes

ano                         int64
clave_entidad               int64
entidad                    object
clave_municipio             int64
municipio                  object
bien_juridico_afectado     object
tipo_de_delito             object
subtipo_delito             object
modalidad                  object
enero                       int64
febrero                   float64
marzo                     float64
abril                     float64
mayo                      float64
junio                     float64
julio                     float64
agosto                    float64
septiembre                float64
octubre                   float64
noviembre                 float64
diciembre                 float64
dtype: object

In [ ]:
#Despues, crearemos una nueva columna llamada ['delitos_totales'] en la cual 
#pondremos la sumatoria de los delitos de todos los meses ocurridos en ese año
data_municipal_delitos_nacional['delitos_totales'] = data_municipal_delitos_nacional.loc[:,['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']].sum(axis=1)
data_municipal_delitos_nacional['delitos_totales']

0          10.0
1           4.0
2          10.0
3           2.0
4           1.0
           ... 
1588771     0.0
1588772     0.0
1588773     0.0
1588774     0.0
1588775     0.0
Name: delitos_totales, Length: 1588776, dtype: float64

In [ ]:
#Contamos el numero de valores NaN que tenemos
data_municipal_delitos_nacional.isna().sum()

ano                            0
clave_entidad                  0
entidad                        0
clave_municipio                0
municipio                      0
bien_juridico_afectado         0
tipo_de_delito                 0
subtipo_delito                 0
modalidad                      0
enero                          0
febrero                   242158
marzo                     242158
abril                     242158
mayo                      242158
junio                     242158
julio                     242158
agosto                    242158
septiembre                242158
octubre                   242158
noviembre                 242158
diciembre                 242158
delitos_totales                0
dtype: int64

In [ ]:
#Vemos que solamente tenemos NaN en los meses(sin contar enero), lo cual nos dice que esto se puede deber a que
#son meses que todavia no sucedian(feb-dic 2021) a la hora de hacer la base de datos, esto lo podemos ver obteniendo
#los indices de todos los registros con valores NaN, viendose que todos son del año actual.
#NOTA: la BBDD no esta incompleta, solo que todavia no suceden esos meses.

#Obteniendo indices
index = data_municipal_delitos_nacional['febrero'].index[data_municipal_delitos_nacional['febrero'].apply(np.isnan)]
#accesando a ellos
data_municipal_delitos_nacional.loc[index].head(3)

ano  clave_entidad  ... diciembre  delitos_totales
1346618  2021              1  ...       NaN              1.0
1346619  2021              1  ...       NaN              0.0
1346620  2021              1  ...       NaN              0.0

[3 rows x 22 columns]

In [ ]:
#Ya que esto afecta a la hora de hacer agregaciones, trabajaremos con datos 2015-2020
data_municipal_delitos_2015_2020 = data_municipal_delitos_nacional[data_municipal_delitos_nacional['ano'] < 2021].copy()

#Confirmamos que ya no tenemos NaNs
data_municipal_delitos_2015_2020.isna().sum()

ano                       0
clave_entidad             0
entidad                   0
clave_municipio           0
municipio                 0
bien_juridico_afectado    0
tipo_de_delito            0
subtipo_delito            0
modalidad                 0
enero                     0
febrero                   0
marzo                     0
abril                     0
mayo                      0
junio                     0
julio                     0
agosto                    0
septiembre                0
octubre                   0
noviembre                 0
diciembre                 0
delitos_totales           0
dtype: int64

In [ ]:
#Ya que tenemos todos los datos de nuestras columnas correctos, podemos empezar haciendo funciones de agregacion
#Para obtener informacion relevante, como el promedio, el minimo, el maximo, la desviacion estandar y sumatoria
#de los delitos realizados en esos meses o delitos totales por municipio

data_municipal_delitos_2015_2020[['delitos_totales','enero','febrero','marzo','abril','mayo','junio','julio',
                                  'agosto','septiembre','octubre', 'noviembre', 'diciembre']].agg(['max','min', 'sum','mean','std'])

delitos_totales          enero  ...      noviembre      diciembre
max      1.233400e+04    1146.000000  ...    1156.000000    1394.000000
min      0.000000e+00       0.000000  ...       0.000000       0.000000
sum      1.126002e+07  894267.000000  ...  928524.000000  893183.000000
mean     8.361702e+00       0.664084  ...       0.689523       0.663279
std      9.557701e+01       7.906211  ...       7.987917       7.918962

[5 rows x 13 columns]

In [ ]:
#Vemos que hay unos meses donde el minimo es -1, esto es debido a un error,
#por lo que crearemos una funcion para cambiar valores negativos por 0

def checador_valores_negativos(num):
  if num < 0:
    return 0
  else:
    return num

#luego aplicamos esta funcion a las columnas
data_municipal_delitos_2015_2020['mayo'] = data_municipal_delitos_2015_2020['mayo'].apply(checador_valores_negativos)
data_municipal_delitos_2015_2020['septiembre'] = data_municipal_delitos_2015_2020['septiembre'].apply(checador_valores_negativos)

In [ ]:
#Despues volvemos a checar los valores minimos para confirmar que ya no tenemos negativos
data_municipal_delitos_2015_2020[['delitos_totales','enero','febrero','marzo','abril','mayo','junio','julio',
                                  'agosto','septiembre','octubre', 'noviembre', 'diciembre']].agg(min)

delitos_totales    0.0
enero              0.0
febrero            0.0
marzo              0.0
abril              0.0
mayo               0.0
junio              0.0
julio              0.0
agosto             0.0
septiembre         0.0
octubre            0.0
noviembre          0.0
diciembre          0.0
dtype: float64

In [ ]:
#Ya que tenemos todo en orden y tenemos los datos limpios podemos empezar a hacer agrupaciones
#Para  obtener datos aun mas relevantes

#Delitos totales reportados por año
data_municipal_delitos_2015_2020.groupby('ano')['delitos_totales'].sum()

ano
2015    1657803.0
2016    1761830.0
2017    1939497.0
2018    1989930.0
2019    2069787.0
2020    1841171.0
Name: delitos_totales, dtype: float64

In [ ]:
#Delitos totales reportados por entidad ordenados de mayor a menor por año
data_municipal_delitos_2015_2020.groupby(['ano','entidad'])[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])


delitos_totales
ano  entidad                          
2015 México                   323525.0
     Ciudad de México         169701.0
     Baja California          119944.0
     Guanajuato                95782.0
     Jalisco                   95331.0
...                                ...
2020 Chiapas                   17269.0
     Yucatán                    8417.0
     Nayarit                    4165.0
     Tlaxcala                   4141.0
     Campeche                   2003.0

[192 rows x 1 columns]

In [ ]:
#Delitos totales reportados agrupados por tipo de delito a lo largo de 5 años
data_municipal_delitos_2015_2020.groupby('tipo_de_delito')['delitos_totales'].sum().sort_values(ascending=False)

tipo_de_delito
Robo                                                                             4323925.0
Lesiones                                                                         1200288.0
Violencia familiar                                                               1061280.0
Otros delitos del Fuero Común                                                    1052710.0
Daño a la propiedad                                                               757240.0
Amenazas                                                                          530852.0
Fraude                                                                            397776.0
Narcomenudeo                                                                      313144.0
Homicidio                                                                         240603.0
Despojo                                                                           150706.0
Abuso de confianza                                                         

In [ ]:
#Tendencia de feminicidio a lo largo de 5 años
data_municipal_delitos_2015_2020[data_municipal_delitos_2015_2020['tipo_de_delito'] == 'Feminicidio'].groupby('ano')['delitos_totales'].sum()

ano
2015    411.0
2016    605.0
2017    742.0
2018    893.0
2019    943.0
2020    939.0
Name: delitos_totales, dtype: float64

In [ ]:
#Tendencia por entidad de acoso sexual/abuso sexual/violacion/feminicidio a lo largo de 5 años
lista_acoso_violacion = ['Abuso sexual','Violación simple', 'Violación equiparada', 'Acoso sexual', 
                         'Violencia de género en todas sus modalidades distinta a la violencia familiar',
                         'Hostigamiento sexual', 'Feminicidio' ]

data_municipal_delitos_2015_2020[data_municipal_delitos_2015_2020['tipo_de_delito'].isin(lista_acoso_violacion)].groupby('ano')['delitos_totales'].sum()

ano
2015    28548.0
2016    33381.0
2017    35055.0
2018    41333.0
2019    51142.0
2020    51263.0
Name: delitos_totales, dtype: float64

In [ ]:
#Municipios con mayores reportes de feminicidio en el transcurso de 5 años
feminicidios_por_municipio = data_municipal_delitos_2015_2020[data_municipal_delitos_2015_2020['tipo_de_delito'] == 'Feminicidio'].groupby(['ano','municipio'])
feminicidios_por_municipio_ordenados = feminicidios_por_municipio[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])
feminicidios_por_municipio_ordenados


delitos_totales
ano  municipio                            
2015 Iztapalapa                       16.0
     Guadalajara                      14.0
     Ecatepec de Morelos               7.0
     Hermosillo                        7.0
     Tlajomulco de Zúñiga              7.0
...                                    ...
2020 Zoquiapan                         0.0
     Zozocolco de Hidalgo              0.0
     Zumpahuacán                       0.0
     Álamo Temapache                   0.0
     Ánimas Trujano                    0.0

[12882 rows x 1 columns]

In [ ]:
#Principales 5 municipios con reportes de feminicidios en 2020
feminicidios_por_municipio_ordenados.filter(like='2020', axis=0)

delitos_totales
ano  municipio                            
2020 Juárez                           26.0
     Tijuana                          18.0
     Monterrey                        17.0
     Culiacán                         13.0
     Zapopan                          13.0
...                                    ...
     Zoquiapan                         0.0
     Zozocolco de Hidalgo              0.0
     Zumpahuacán                       0.0
     Álamo Temapache                   0.0
     Ánimas Trujano                    0.0

[2326 rows x 1 columns]

In [ ]:
#Entidades con mayores reportes de feminicidio en el transcurso de 5 años
feminicidios_por_entidad = data_municipal_delitos_2015_2020[data_municipal_delitos_2015_2020['tipo_de_delito'] == 'Feminicidio'].groupby(['ano','entidad'])
feminicidios_por_entidad_ordenados = feminicidios_por_entidad[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])
feminicidios_por_entidad_ordenados

delitos_totales
ano  entidad                                         
2015 Jalisco                                     62.0
     México                                      59.0
     Ciudad de México                            56.0
     Veracruz de Ignacio de la Llave             40.0
     Chiapas                                     36.0
...                                               ...
2020 Tlaxcala                                     6.0
     Yucatán                                      6.0
     Baja California Sur                          4.0
     Aguascalientes                               3.0
     Campeche                                     3.0

[192 rows x 1 columns]

In [ ]:
#Principales 5 entidades con reportes de feminicidios en 2020
feminicidios_por_entidad_ordenados.filter(like='2020', axis=0).head(5)

delitos_totales
ano  entidad                                         
2020 México                                     150.0
     Veracruz de Ignacio de la Llave             84.0
     Nuevo León                                  67.0
     Jalisco                                     66.0
     Ciudad de México                            64.0

In [ ]:
#Principales municipios con reportes de acoso sexual/violencia de genero/violacion

lista_acoso_violacion = ['Abuso sexual','Violación simple', 'Violación equiparada', 'Acoso sexual', 
                         'Violencia de género en todas sus modalidades distinta a la violencia familiar',
                         'Hostigamiento sexual']
datos_acoso_violacion_municipal = data_municipal_delitos_2015_2020.loc[data_municipal_delitos_2015_2020['tipo_de_delito'].isin(lista_acoso_violacion)]
datos_acoso_violacion_municipal_ordenados = datos_acoso_violacion.groupby(['ano','municipio'])[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])
datos_acoso_violacion_municipal_ordenados.filter(like='2020', axis=0).head(5)

delitos_totales
ano  municipio                           
2020 Juárez                        1314.0
     Tijuana                       1128.0
     Ecatepec de Morelos           1021.0
     Cuauhtémoc                    1017.0
     Querétaro                      968.0

In [ ]:
#Principales entidades con reportes de acoso sexual/violencia de genero/violacion
lista_acoso_violacion = ['Abuso sexual','Violación simple', 'Violación equiparada', 'Acoso sexual', 
                         'Violencia de género en todas sus modalidades distinta a la violencia familiar',
                         'Hostigamiento sexual']
datos_acoso_violacion_entidad = data_municipal_delitos_2015_2020.loc[data_municipal_delitos_2015_2020['tipo_de_delito'].isin(lista_acoso_violacion)]
datos_acoso_violacion_entidad_ordenados = datos_acoso_violacion.groupby(['ano','entidad'])[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])
datos_acoso_violacion_entidad_ordenados.filter(like='2020', axis=0).head(5)

delitos_totales
ano  entidad                          
2020 México                     8045.0
     Ciudad de México           5691.0
     Nuevo León                 2892.0
     Jalisco                    2829.0
     Chihuahua                  2567.0

In [ ]:
#Tendencia por entidad de acoso sexual/abuso sexual/violacion/feminicidio a lo largo de 5 años
lista_acoso_violacion = ['Abuso sexual','Violación simple', 'Violación equiparada', 'Acoso sexual', 
                         'Violencia de género en todas sus modalidades distinta a la violencia familiar',
                         'Hostigamiento sexual']
datos_acoso_violacion = data_municipal_delitos_2015_2020.loc[data_municipal_delitos_2015_2020['tipo_de_delito'].isin(lista_acoso_violacion)]
datos_acoso_violacion.groupby(['ano','entidad'])[['delitos_totales']].sum().sort_values(['ano', 'delitos_totales'], ascending=[True,False])

delitos_totales
ano  entidad                          
2015 México                     3401.0
     Baja California            2443.0
     Ciudad de México           2390.0
     Chihuahua                  2138.0
     Jalisco                    2099.0
...                                ...
2020 Aguascalientes              380.0
     Campeche                    257.0
     Nayarit                     161.0
     Yucatán                     112.0
     Tlaxcala                     68.0

[192 rows x 1 columns]

### **Limpieza y análisis de `personas_desaparecidas_al2018_ff.csv `**

Contiene el total de registros de personas relacionadas con averiguaciones previas y carpetas de investigación del fuero federal iniciadas en el periodo comprendido entre enero de 2014 y abril de 2018, y que permanecen sin localizar al corte del 30 de abril de 2018.Publicado por el Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública.

Esta base de datos contiene variables como nombre, apellidos, entidad y  municipio donde se vio por ultima vez, sexo, edad , fecha cuando se vió por ultima vez y fecha cuando se hizo el reporte.



In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np 

In [ ]:
#Lectura de archivos .csv
path_desaparecidos_ff = '/content/personas_desaparecidas_al2018_ff.csv'
data_desaparecidos_ff = pd.read_csv(path_desaparecidos_ff, encoding = "latin")
data_desaparecidos_ff.head(2)

Fecha en que se le vio por ultima vez  ... Entidad donde se recibio la denuncia
0                            2014-09-26  ...                     CIUDAD DE MÉXICO
1                            2014-09-26  ...                     CIUDAD DE MÉXICO

[2 rows x 16 columns]

In [ ]:
#Obtenemos el numero de registros y columnas que hay en el dataframe
data_desaparecidos_ff.shape

(1170, 16)

In [ ]:
#Obtenemos el nombre de las columnas
data_desaparecidos_ff.columns

Index(['Fecha en que se le vio por ultima vez', 'Nombre(s)',
       'Apellido paterno', 'Apellido materno',
       'Pais en que se le vio por ultima vez',
       'Entidad en que se le vio por ultima vez', 'Clave de entidad',
       'Municipio en que se le vio por ultima vez', 'Pais de nacimiento',
       'Nacionalidad', 'Sexo', 'Edad', 'Tipo de Lugar',
       'Autoridad que recibio la denuncia', 'Fecha de la denuncia',
       'Entidad donde se recibio la denuncia'],
      dtype='object')

In [ ]:
#Creamos un diccionario con los nuevos nombres de las columnas
nuevas_columnas = {
    'Fecha en que se le vio por ultima vez':'fecha_visto_ultima_vez',
     'Nombre(s)':'nombres',
     'Apellido paterno':'apellido_paterno',
     'Apellido materno':'apellido_materno',
     'Pais en que se le vio por ultima vez':'pais_visto_ultima_vez',
     'Entidad en que se le vio por ultima vez':'entidad_visto_ultima_vez',
     'Clave de entidad':'clave_entidad',
     'Municipio en que se le vio por ultima vez':'municipio_visto', 
     'Pais de nacimiento':'pais_de_nacimiento',
     'Nacionalidad':'nacionalidad', 
     'Sexo':'sexo',
     'Edad':'edad',
     'Tipo de Lugar':'tipo_de_lugar',
     'Autoridad que recibio la denuncia':'autoridad_denuncia', 
     'Fecha de la denuncia':'fecha_denuncia',
     'Entidad donde se recibio la denuncia':'entidad_denuncia'
}

#Cambiamos el nombre de las columnas
data_desaparecidos_ff = data_desaparecidos_ff.rename(columns=nuevas_columnas)
data_desaparecidos_ff.head(2)

fecha_visto_ultima_vez     nombres  ... fecha_denuncia  entidad_denuncia
0             2014-09-26  LUIS ANGEL  ...     2015-11-09  CIUDAD DE MÉXICO
1             2014-09-26        ADAN  ...     2015-11-09  CIUDAD DE MÉXICO

[2 rows x 16 columns]

In [ ]:
#Analizamos los tipos de datos que tenemos por columna
data_desaparecidos_ff.dtypes

fecha_visto_ultima_vez      object
nombres                     object
apellido_paterno            object
apellido_materno            object
pais_visto_ultima_vez       object
entidad_visto_ultima_vez    object
clave_entidad                int64
municipio_visto             object
pais_de_nacimiento          object
nacionalidad                object
sexo                        object
edad                        object
tipo_de_lugar               object
autoridad_denuncia          object
fecha_denuncia              object
entidad_denuncia            object
dtype: object

In [ ]:
#Cambiaremos el tipo de dato de edad a dato numerico, pero antes cambiaremos las edades
#que aparecen como no disponible a NaN 
data_desaparecidos_ff['edad'] = data_desaparecidos_ff['edad'].replace(to_replace='NO DISPONIBLE', value=np.nan)
data_desaparecidos_ff['edad'] = pd.to_numeric(data_desaparecidos_ff['edad'])

In [ ]:
#Despues cambiaremos la columna fecha_visto_ultima_vez y fecha_denuncia por tipo datetime
data_desaparecidos_ff['fecha_visto_ultima_vez'] = pd.to_datetime(data_desaparecidos_ff['fecha_visto_ultima_vez'], yearfirst=True, errors='coerce')
data_desaparecidos_ff['fecha_denuncia'] = pd.to_datetime(data_desaparecidos_ff['fecha_denuncia'], yearfirst=True, errors='coerce')

In [ ]:
#Despues observamos cuantos valores con NaN hay
data_desaparecidos_ff = data_desaparecidos_ff.replace('NO DISPONIBLE',np.nan)
data_desaparecidos_ff.isna().sum()

fecha_visto_ultima_vez        9
nombres                       0
apellido_paterno              0
apellido_materno              1
pais_visto_ultima_vez        29
entidad_visto_ultima_vez     33
clave_entidad                 0
municipio_visto              57
pais_de_nacimiento           16
nacionalidad                 16
sexo                          0
edad                        284
tipo_de_lugar                 0
autoridad_denuncia            0
fecha_denuncia                0
entidad_denuncia              0
dtype: int64

In [ ]:
#Hacemos un drop de todos los registros que contengan NaN 
#Y observamos que ya no hay valores perdidos
data_desaparecidos_ff = data_desaparecidos_ff.dropna(axis=0,how='any')
data_desaparecidos_ff.isna().sum()

fecha_visto_ultima_vez      0
nombres                     0
apellido_paterno            0
apellido_materno            0
pais_visto_ultima_vez       0
entidad_visto_ultima_vez    0
clave_entidad               0
municipio_visto             0
pais_de_nacimiento          0
nacionalidad                0
sexo                        0
edad                        0
tipo_de_lugar               0
autoridad_denuncia          0
fecha_denuncia              0
entidad_denuncia            0
dtype: int64

In [ ]:
#Despues crearemos una columna que sea la diferencia de dias entre la fecha que se vio por ultima vez y la fecha de la denuncia
#llamando a la columna diferencia_ultima_vez_y_denuncia

data_desaparecidos_ff['diferencia_ultima_vez_y_denuncia'] = abs((data_desaparecidos_ff['fecha_denuncia'] - data_desaparecidos_ff['fecha_visto_ultima_vez']).dt.days)
data_desaparecidos_ff.head()

fecha_visto_ultima_vez  ... diferencia_ultima_vez_y_denuncia
0             2014-09-26  ...                              409
1             2014-09-26  ...                              409
2             2014-03-05  ...                             1224
4             2016-09-25  ...                              193
5             2013-05-16  ...                              684

[5 rows x 17 columns]

In [ ]:
#Confirmamos que todos los datos tengan el tipo correcto
data_desaparecidos_ff.dtypes

fecha_visto_ultima_vez              datetime64[ns]
nombres                                     object
apellido_paterno                            object
apellido_materno                            object
pais_visto_ultima_vez                       object
entidad_visto_ultima_vez                    object
clave_entidad                                int64
municipio_visto                             object
pais_de_nacimiento                          object
nacionalidad                                object
sexo                                        object
edad                                       float64
tipo_de_lugar                               object
autoridad_denuncia                          object
fecha_denuncia                      datetime64[ns]
entidad_denuncia                            object
diferencia_ultima_vez_y_denuncia             int64
dtype: object

In [ ]:
#Ya que tenemos todos los datos de nuestras columnas correctos, podemos empezar haciendo funciones de agregacion
#Para obtener informacion relevante, como el promedio, el minimo, el maximo y la desviacion estandar

data_desaparecidos_ff[['edad','diferencia_ultima_vez_y_denuncia']].agg(['mean','min','max','std'])

edad  diferencia_ultima_vez_y_denuncia
mean  29.378092                       1175.755006
min    0.000000                          0.000000
max   86.000000                      15395.000000
std   12.011769                       1596.265638

In [ ]:
#Como dato curioso, vemos que el valor maximo de la columna diferencia_ultima_vez_y_denuncia es de 15395
#si buscamos el registro vemos que la ultima vez que se vio es 1973 y la denuncia fue en el 2016
data_desaparecidos_ff[data_desaparecidos_ff['diferencia_ultima_vez_y_denuncia'] == 15395]

fecha_visto_ultima_vez  ... diferencia_ultima_vez_y_denuncia
178             1973-11-18  ...                            15395

[1 rows x 17 columns]

In [ ]:
#Ahora empezaremos a hacer agrupaciones para obtener datos aun mas relevantes
#Personas desaparecidas agrupadas por año en que se recibieron las denuncias, fuero federal
data_desaparecidos_ff.groupby(data_desaparecidos_ff['fecha_denuncia'].dt.year).size()

fecha_denuncia
2014    271
2015    341
2016    127
2017     92
2018     18
dtype: int64

In [ ]:
#Personas desaparecidas agrupadas por sexo, fuero federal
data_desaparecidos_ff.groupby('sexo').size()


sexo
HOMBRE    708
MUJER     141
dtype: int64

In [ ]:
#Personas desaparecidas agrupadas por nacionalidad, fuero federal
data_desaparecidos_ff.groupby('nacionalidad').size().sort_values(ascending=False)

nacionalidad
MÉXICO         735
GUATEMALA       41
HONDURAS        25
EL SALVADOR     13
COLOMBIA        13
INDIA            5
PERU             4
NICARAGUA        3
ITALIA           2
ECUADOR          2
BRASIL           2
POLONIA          1
CUBA             1
COSTA RICA       1
ARGENTINA        1
dtype: int64

In [ ]:
#Personas desaparecidas agrupadas por rango de edad, fuero federal
bins = [-1, 10, 20,30,40,50,60, np.inf]
labels=['0-10','10-20','20-30','30-40','40-50', '50-60', '60+']
data_desaparecidos_ff_edades =data_desaparecidos_ff.groupby(pd.cut(data_desaparecidos_ff['edad'], bins=bins, labels=labels)).size().reset_index(name='count')
print (data_desaparecidos_ff_edades)


    edad  count
0   0-10     28
1  10-20    172
2  20-30    319
3  30-40    190
4  40-50     91
5  50-60     39
6    60+     10


In [ ]:
#Autoridades que recibieron mas denuncias
data_desaparecidos_ff.groupby('autoridad_denuncia').size().sort_values(ascending=False)

autoridad_denuncia
SDHPDSC/UEBPD                       413
SDHPDSC/FEBPD                       198
SDHPDSC/UIDPM                       108
SDHPDSC/OICI                         43
OAXACA/OAXACA                        18
TAMAULIPAS/TAMPICO                   11
SEIDO/UEIDMS                          7
VERACRUZ/VERACRUZ                     6
SDHPDSC/FEVIMTRA                      6
SEIDF/CGI                             4
SDHPDSC/FEIDDF                        3
TAMAULIPAS/REYNOSA                    3
TAMAULIPAS/MATAMOROS                  3
TAMAULIPAS/NUEVO LAREDO               3
SEIDO/UEIDCS                          2
SEIDF/UEIDAPLE                        2
SDHAVSC/USBPD                         1
CHIAPAS/SAN CRISTÓBAL                 1
COLIMA/COLIMA                         1
DISTRITO FEDERAL/DGCAP                1
HIDALGO/PACHUCA                       1
JALISCO/AUTLÁN                        1
JALISCO/GUADALAJARA                   1
QUINTANA ROO/CANCÚN                   1
SJAI/UEDE            

In [ ]:
#Entidades que recibieron mas denuncias
data_desaparecidos_ff.groupby('entidad_denuncia').size().sort_values(ascending=False)

entidad_denuncia
CIUDAD DE MÉXICO                   782
TAMAULIPAS                          28
OAXACA                              18
VERACRUZ DE IGNACIO DE LA LLAVE      7
TABASCO                              2
NUEVO LEÓN                           2
JALISCO                              2
CHIAPAS                              2
BAJA CALIFORNIA                      2
SINALOA                              1
QUINTANA ROO                         1
HIDALGO                              1
COLIMA                               1
dtype: int64

In [ ]:
#Entidades en las que se realizaron mas denuncias, agrupadas por sexo, fuero federal
data_desaparecidos_ff.groupby('sexo')['entidad_denuncia'].value_counts()

sexo    entidad_denuncia               
HOMBRE  CIUDAD DE MÉXICO                   659
        TAMAULIPAS                          22
        OAXACA                               9
        VERACRUZ DE IGNACIO DE LA LLAVE      7
        BAJA CALIFORNIA                      2
        JALISCO                              2
        NUEVO LEÓN                           2
        CHIAPAS                              1
        HIDALGO                              1
        QUINTANA ROO                         1
        SINALOA                              1
        TABASCO                              1
MUJER   CIUDAD DE MÉXICO                   123
        OAXACA                               9
        TAMAULIPAS                           6
        CHIAPAS                              1
        COLIMA                               1
        TABASCO                              1
Name: entidad_denuncia, dtype: int64

In [ ]:
#Incidencia de personas desaparecidas con el paso de los años
data_desaparecidos_ff.groupby([data_desaparecidos_ff['fecha_visto_ultima_vez'].dt.year])['sexo'].value_counts()

fecha_visto_ultima_vez  sexo  
1973                    HOMBRE      1
1974                    HOMBRE      2
1977                    HOMBRE      2
1981                    HOMBRE      1
1982                    HOMBRE      1
1987                    HOMBRE      1
1992                    HOMBRE      1
1995                    HOMBRE      1
1996                    MUJER       1
2000                    HOMBRE      1
2001                    HOMBRE      1
2002                    HOMBRE      3
2004                    HOMBRE      2
                        MUJER       1
2005                    HOMBRE      9
                        MUJER       1
2006                    HOMBRE      7
                        MUJER       4
2007                    HOMBRE     18
                        MUJER       3
2008                    HOMBRE     21
                        MUJER       4
2009                    HOMBRE     21
                        MUJER       7
2010                    HOMBRE     82
                   

### **Limpieza y análisis de `personas_desaparecidas_al2018_fc.csv`**

Contiene el total de registros de personas relacionadas con averiguaciones previas, carpetas de investigación o actas circunstanciadas del fuero común que permanecen sin localizar al corte del 30 de abril del 2018.
Publicado por el Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública.

Esta base de datos contiene variables como fecha, hora, pais, entidad y municipio en el que se le vio por ultima vez, sexo edad, estatura, etnia, discapacidad y dependencia que envió la informacion.

In [ ]:
#Importando las paqueterías necesarias 
import pandas as pd 
import os 
import numpy as np 

In [ ]:
#Lectura de archivos .csv
path_personas_desaparecidas_2018_fc = '/content/personas_desaparecidas_al2018_fc.csv'
df_personas_desaparecidas_2018_fc = pd.read_csv(path_personas_desaparecidas_2018_fc, encoding = "latin")
df_personas_desaparecidas_2018_fc.head(2)

Fecha en que se le vio por ultima vez  ... Dependencia que envio la informacion
0                            2012-03-18  ...                         FGE - SONORA
1                            2007-02-05  ...               FGJ - ESTADO DE MEXICO

[2 rows x 15 columns]

In [ ]:
#Obtenemos el numero de registros y columnas que hay en el dataframe
df_personas_desaparecidas_2018_fc.shape

(36265, 15)

In [ ]:
#Obtenemos el nombre de las columnas
df_personas_desaparecidas_2018_fc.columns

Index(['Fecha en que se le vio por ultima vez',
       'Hora en que se le vio por ultima vez',
       'Pais en que se le vio por ultima vez',
       'Entidad en que se le vio por ultima vez',
       'Municipio en que se le vio por ultima vez',
       'Localidad en que se le vio por ultima vez', 'Nacionalidad', 'Estatura',
       'Complexion', 'Sexo', 'Edad', 'Descripcion de senas particulares',
       'Etnia', 'Discapacidad', 'Dependencia que envio la informacion'],
      dtype='object')

In [ ]:
#Creamos un diccionario con los nuevos nombres de las columnas
nuevas_columnas = {
    'Fecha en que se le vio por ultima vez': 'fecha_visto_ultima_vez',
       'Hora en que se le vio por ultima vez': 'hora_visto_ultima_vez',
       'Pais en que se le vio por ultima vez': 'pais_visto_ultima_vez',
       'Entidad en que se le vio por ultima vez': 'entidad_visto_ultima_vez',
       'Municipio en que se le vio por ultima vez': 'municipio_visto_ultima_vez',
       'Localidad en que se le vio por ultima vez':'localidad_visto_ultima_vez',
       'Nacionalidad': 'nacionalidad',
       'Estatura':'estatura',
       'Complexion': 'complexion',
       'Sexo': 'sexo',
       'Edad':'edad',
       'Descripcion de senas particulares': 'senas_particulares',
       'Etnia':'etnia',
       'Discapacidad':'discapacidad',
       'Dependencia que envio la informacion':'dependencia_informacion'    
}

#Cambiamos el nombre de las columnas
df_personas_desaparecidas_2018_fc = df_personas_desaparecidas_2018_fc.rename(columns=nuevas_columnas)
df_personas_desaparecidas_2018_fc.head(2)

fecha_visto_ultima_vez  ... dependencia_informacion
0             2012-03-18  ...            FGE - SONORA
1             2007-02-05  ...  FGJ - ESTADO DE MEXICO

[2 rows x 15 columns]

In [ ]:
#Analizamos los tipos de datos que tenemos por columna
df_personas_desaparecidas_2018_fc.dtypes

fecha_visto_ultima_vez        object
hora_visto_ultima_vez         object
pais_visto_ultima_vez         object
entidad_visto_ultima_vez      object
municipio_visto_ultima_vez    object
localidad_visto_ultima_vez    object
nacionalidad                  object
estatura                      object
complexion                    object
sexo                          object
edad                          object
senas_particulares            object
etnia                         object
discapacidad                  object
dependencia_informacion       object
dtype: object

In [ ]:
#Combinaremos las columnas fecha_visto_ultima_vez y hora_visto_ultima_vez, creaundo una nueva columna 
#para facilitar su uso y despues le cambiamos el tipo de dato a datetime
df_personas_desaparecidas_2018_fc['fecha_hora_visto_ultima_vez'] = df_personas_desaparecidas_2018_fc['fecha_visto_ultima_vez'] + " " +df_personas_desaparecidas_2018_fc['hora_visto_ultima_vez']
df_personas_desaparecidas_2018_fc = df_personas_desaparecidas_2018_fc[ ['fecha_hora_visto_ultima_vez'] + [ col for col in df_personas_desaparecidas_2018_fc.columns if col != 'fecha_hora_visto_ultima_vez' ] ]
df_personas_desaparecidas_2018_fc['fecha_hora_visto_ultima_vez'] = pd.to_datetime(df_personas_desaparecidas_2018_fc['fecha_hora_visto_ultima_vez'], errors = 'coerce')
df_personas_desaparecidas_2018_fc = df_personas_desaparecidas_2018_fc.drop(labels=['fecha_visto_ultima_vez','hora_visto_ultima_vez'], axis=1)
df_personas_desaparecidas_2018_fc.head(1)

fecha_hora_visto_ultima_vez  ... dependencia_informacion
0         2012-03-18 05:00:00  ...            FGE - SONORA

[1 rows x 14 columns]

In [ ]:
#Cambiaremos el tipo de dato de la columna estatura, para esto primero cambiaremos todos
#los valores NO ESPECIFICADO por NaN

df_personas_desaparecidas_2018_fc['estatura'] = df_personas_desaparecidas_2018_fc['estatura'].replace(to_replace='NO ESPECIFICADO', value=np.nan)
df_personas_desaparecidas_2018_fc['estatura'] = df_personas_desaparecidas_2018_fc['estatura'].replace(to_replace='no ESPECIFICADO', value=np.nan)
df_personas_desaparecidas_2018_fc['estatura'] = pd.to_numeric(df_personas_desaparecidas_2018_fc['estatura'])

In [ ]:
#Realizamos el mismo cambio en la columna edad
df_personas_desaparecidas_2018_fc['edad'] = df_personas_desaparecidas_2018_fc['edad'].replace(to_replace='NO ESPECIFICADO', value=np.nan)
df_personas_desaparecidas_2018_fc['edad'] = df_personas_desaparecidas_2018_fc['edad'].replace(to_replace='no ESPECIFICADO', value=np.nan)
df_personas_desaparecidas_2018_fc['edad'] = pd.to_numeric(df_personas_desaparecidas_2018_fc['edad'])

In [ ]:
#Observamos que ya tenemos las columnas con el tipo de dato correcto
df_personas_desaparecidas_2018_fc.dtypes

fecha_hora_visto_ultima_vez    datetime64[ns]
pais_visto_ultima_vez                  object
entidad_visto_ultima_vez               object
municipio_visto_ultima_vez             object
localidad_visto_ultima_vez             object
nacionalidad                           object
estatura                              float64
complexion                             object
sexo                                   object
edad                                  float64
senas_particulares                     object
etnia                                  object
discapacidad                           object
dependencia_informacion                object
dtype: object

In [ ]:
#Ahora normalizamos todos los valores no especificados 
df_personas_desaparecidas_2018_fc = df_personas_desaparecidas_2018_fc.replace(to_replace= 'No Especificado', value= 'NO ESPECIFICADO')

In [ ]:
#Creamos una funcion para transformar todas las estaturas en metros
def cm_a_metros(estatura):
  if (estatura > 0 and estatura < 3) or estatura == np.nan:
    return estatura
  else:
    return (estatura / 100)


In [ ]:
#Aplicamos la funcion creada a la columna de estatura
df_personas_desaparecidas_2018_fc['estatura'] = df_personas_desaparecidas_2018_fc['estatura'].apply(cm_a_metros)

In [ ]:
#Ya que tenemos todos los datos de nuestras columnas correctos, podemos empezar haciendo funciones de agregacion
#Para obtener informacion relevante, como el promedio, el minimo, el maximo y la desviacion estandar

df_personas_desaparecidas_2018_fc.agg({'estatura' : ['mean', 'min','max','std'], 'edad' : ['mean','min', 'max','std']})

estatura        edad
mean  1.638859   30.801655
min   0.300000    1.000000
max   2.040000  103.000000
std   0.162449   15.025777

In [ ]:
#Ahora empezaremos a hacer agrupaciones para obtener datos aun mas relevantes
df_personas_desaparecidas_2018_fc.groupby(['sexo']).size()

sexo
HOMBRE    26938
MUJER      9327
dtype: int64

In [ ]:
df_personas_desaparecidas_2018_fc.groupby(['nacionalidad']).size().sort_values(ascending= False)

nacionalidad
MEXICANA           34016
NO ESPECIFICADO     2040
ESTADOUNIDENSE       124
HONDUREÑA             24
GUATEMALTECO          12
COLOMBIANA             9
SALVADOREÑA            8
VENEZOLANA             4
ITALIANA               3
CUBANA                 3
CANADIENSE             3
ESPAÑOLA               3
HAITIANA               2
PERUANA                2
CHINA                  1
BRASILEÑA              1
ARGENTINA              1
COSTARICENSE           1
FRANCESA               1
DOMINICANA             1
ERITREA                1
HOLANDESA              1
NICARAGUENSE           1
PANAMEÑA               1
PARAGUAYA              1
ALEMANA                1
dtype: int64

In [ ]:
#Dependencia donde se reporta el mayor numero de mujeres desaparecidas

df_personas_desaparecidas_2018_fc.groupby(['dependencia_informacion']).size().sort_values(ascending= False)

dependencia_informacion
PGJ - TAMAULIPAS             5979
FGJ - ESTADO DE MEXICO       3874
FGE - JALISCO                3379
FGE - SINALOA                3025
PGJ - NUEVO LEON             2884
FGE - CHIHUAHUA              2201
FGE - SONORA                 2146
FGE - PUEBLA                 2086
FGE - COAHUILA               1778
FGE - GUERRERO               1502
PGJ - MICHOACAN              1204
PGJ - BAJA CALIFORNIA        1012
PGJ - CIUDAD DE MEXICO        742
PGJ - GUANAJUATO              615
PGJ - COLIMA                  590
FGE - VERACRUZ                514
FGE - ZACATECAS               510
FGE - DURANGO                 406
FGE - QUERETARO               361
FGE - MORELOS                 240
FGE - AGUASCALIENTES          221
FGE - OAXACA                  202
PGJ - HIDALGO                 175
FGE - NAYARIT                 144
FGE - CHIAPAS                 107
FGE - YUCATAN                  98
FGE - TABASCO                  64
FGE - QUINTANA ROO             60
FGE - SAN LUIS POTOSI   

In [ ]:
#Despues observamos cuales etnias tienen mas personas desaparecidas reportadas
df_personas_desaparecidas_2018_fc[df_personas_desaparecidas_2018_fc['etnia'] != 'NO ESPECIFICADO'].groupby(['etnia']).size().sort_values(ascending= False)

etnia
MAYAS                     27
NAHUAS                    18
AMUZGOS OAXACA            13
TLALPANECOS               11
CHATINOS                  11
OTOMIES                   10
TARAHUMARAS - RARAMURI     9
CHICHIMECAS                6
CHINANTECOS                5
SERIS                      4
MIXTECOS                   4
MEXICANEROS                3
HUICHOLES                  2
CHOLES                     2
TOTONACAS                  2
YAQUIS                     2
HUASTECOS                  1
MAMES                      1
PAMES                      1
dtype: int64

In [ ]:
#Agrupando por año para ver cuando se han reportado mas
personas_desaparecidas_por_ano = df_personas_desaparecidas_2018_fc.groupby([df_personas_desaparecidas_2018_fc['fecha_hora_visto_ultima_vez'].dt.year]).size().sort_values(ascending= False)
personas_desaparecidas_por_ano.sort_index(ascending=False)

fecha_hora_visto_ultima_vez
2018.0    1634
2017.0    5426
2016.0    4525
2015.0    3272
2014.0    3790
2013.0    3650
2012.0    3288
2011.0    4064
2010.0    3206
2009.0    1372
2008.0     800
2007.0     620
2006.0      89
2005.0      47
2004.0      15
2003.0      16
2002.0      19
2001.0      13
2000.0      18
1999.0       8
1998.0       9
1997.0       9
1996.0       5
1995.0       2
1994.0       1
1993.0       3
1992.0       1
1991.0       2
1990.0       1
1989.0       4
1988.0       2
1987.0       2
1985.0       2
1984.0       1
1980.0       1
1979.0       3
1978.0       1
1977.0       2
1976.0       1
1972.0       1
1971.0       1
1968.0       1
dtype: int64

In [ ]:
#Aqui se puede observar como con el paso de los años va aumentando el numero de mujeres desaparecidas repiradas
personas_desaparecidas_sexo_fecha = df_personas_desaparecidas_2018_fc.groupby([df_personas_desaparecidas_2018_fc['fecha_hora_visto_ultima_vez'].dt.year])['sexo'].value_counts()
personas_desaparecidas_sexo_fecha.tail(25)

fecha_hora_visto_ultima_vez  sexo  
2006.0                       MUJER       22
2007.0                       HOMBRE     476
                             MUJER      144
2008.0                       HOMBRE     630
                             MUJER      170
2009.0                       HOMBRE    1074
                             MUJER      298
2010.0                       HOMBRE    2732
                             MUJER      474
2011.0                       HOMBRE    3199
                             MUJER      865
2012.0                       HOMBRE    2580
                             MUJER      708
2013.0                       HOMBRE    2837
                             MUJER      813
2014.0                       HOMBRE    2906
                             MUJER      884
2015.0                       HOMBRE    2350
                             MUJER      922
2016.0                       HOMBRE    3046
                             MUJER     1479
2017.0                       HOMBRE    3

In [ ]:
#Principales entidades donde se ve por ultima vez a las mujeres desaparecidas
df_personas_desaparecidas_2018_fc[df_personas_desaparecidas_2018_fc['sexo'] == 'MUJER'].groupby(['entidad_visto_ultima_vez']).size().sort_values(ascending= False)

entidad_visto_ultima_vez
ESTADO DE MEXICO        1785
TAMAULIPAS              1274
PUEBLA                  1046
NUEVO LEON               760
SONORA                   641
BAJA CALIFORNIA          414
SINALOA                  394
JALISCO                  386
COAHUILA DE ZARAGOZA     327
CIUDAD DE MEXICO         327
GUERRERO                 301
MICHOACAN                232
CHIHUAHUA                224
COLIMA                   181
VERACRUZ                 136
AGUASCALIENTES           109
GUANAJUATO               102
OAXACA                    99
MORELOS                   96
QUERETARO                 89
HIDALGO                   71
ZACATECAS                 66
DURANGO                   62
CHIAPAS                   52
TABASCO                   35
QUINTANA ROO              33
YUCATAN                   32
CAMPECHE                  13
SAN LUIS POTOSI           12
NAYARIT                   10
TLAXCALA                  10
NO ESPECIFICADO            4
BAJA CALIFORNIA SUR        4
dtype: int64

In [ ]:
#Dependencia donde se reporta el mayor numero de mujeres desaparecidas
df_personas_desaparecidas_2018_fc[df_personas_desaparecidas_2018_fc['sexo'] == 'MUJER'].groupby(['dependencia_informacion']).size().sort_values(ascending= False)

dependencia_informacion
FGJ - ESTADO DE MEXICO       1778
PGJ - TAMAULIPAS             1270
FGE - PUEBLA                 1050
PGJ - NUEVO LEON              758
FGE - SONORA                  643
PGJ - BAJA CALIFORNIA         412
FGE - SINALOA                 395
FGE - JALISCO                 385
FGE - COAHUILA                337
PGJ - CIUDAD DE MEXICO        328
FGE - GUERRERO                311
PGJ - MICHOACAN               233
FGE - CHIHUAHUA               224
PGJ - COLIMA                  179
FGE - VERACRUZ                133
FGE - AGUASCALIENTES          109
PGJ - GUANAJUATO              101
FGE - OAXACA                   98
FGE - QUERETARO                96
FGE - MORELOS                  95
PGJ - HIDALGO                  69
FGE - ZACATECAS                68
FGE - DURANGO                  57
FGE - CHIAPAS                  52
FGE - TABASCO                  34
FGE - QUINTANA ROO             32
FGE - YUCATAN                  32
FGE - CAMPECHE                 13
FGE - SAN LUIS POTOSI   

### **Limpieza y análisis de `victimas_nacional_2015_ene2021.csv `**

Este dataset fue obtenido de Datos Abiertos de Incidencia Delictiva, contiene datos de las víctimas registradas a nivel nacional durante 2015-enero 2021.

In [ ]:
#Importando las paqueterías necesarias
import pandas as pd
import os
import numpy as np 

In [ ]:
#Lectura de los archivos .csv . NOTA: Los archivos se encuentran en una carpeta de Drive que facilita su lectura en este Notebook.
#Adicionalmente cada dataset analizado se encuentra en formato .zip en el Github del equipo disponibles para su descarga. 
#Fue obtenido de [III] Gobierno de la Ciudad de México, Portal de datos abiertos .
ruta_archivo = "/content/drive/MyDrive/Datasets/Datasets/victimas_nacional_2015_ene2021.csv"
victimas_nacional_2015_ene2021 = "victimas_nacional_2015_ene2021.csv"
df_victimas_nacional = pd.read_csv(ruta_archivo,encoding = "latin1")

### **Explorando el dataset.**

In [ ]:
#Exploración del dataset 
df_victimas_nacional.head(3)

Año  Clave_Ent         Entidad  ... Octubre Noviembre Diciembre
0  2015          1  Aguascalientes  ...     0.0       0.0       0.0
1  2015          1  Aguascalientes  ...     0.0       0.0       0.0
2  2015          1  Aguascalientes  ...     0.0       0.0       0.0

[3 rows x 21 columns]

In [ ]:
df_victimas_nacional.tail(3) #Se puede observar que existen valores NaN a limpiar y algunos datos disponibles

Año  Clave_Ent    Entidad  ... Octubre Noviembre Diciembre
51517  2021         32  Zacatecas  ...     NaN       NaN       NaN
51518  2021         32  Zacatecas  ...     NaN       NaN       NaN
51519  2021         32  Zacatecas  ...     NaN       NaN       NaN

[3 rows x 21 columns]

In [ ]:
#Exploración del dataset
print(df_victimas_nacional.dtypes) #Observamos todas las columnas y el tipo de dato que almacenan 
df_victimas_nacional.shape  #Para obtener el número de registros y columnas 

Año                         int64
Clave_Ent                   int64
Entidad                    object
Bien jurídico afectado     object
Tipo de delito             object
Subtipo de delito          object
Modalidad                  object
Sexo                       object
Rango de edad              object
Enero                       int64
Febrero                   float64
Marzo                     float64
Abril                     float64
Mayo                      float64
Junio                     float64
Julio                     float64
Agosto                    float64
Septiembre                float64
Octubre                   float64
Noviembre                 float64
Diciembre                 float64
dtype: object


(51520, 21)

In [ ]:
df_victimas_nacional.info() #Obteniendo la información del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51520 entries, 0 to 51519
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Año                     51520 non-null  int64  
 1   Clave_Ent               51520 non-null  int64  
 2   Entidad                 51520 non-null  object 
 3   Bien jurídico afectado  51520 non-null  object 
 4   Tipo de delito          51520 non-null  object 
 5   Subtipo de delito       51520 non-null  object 
 6   Modalidad               51520 non-null  object 
 7   Sexo                    51520 non-null  object 
 8   Rango de edad           51520 non-null  object 
 9   Enero                   51520 non-null  int64  
 10  Febrero                 44160 non-null  float64
 11  Marzo                   44160 non-null  float64
 12  Abril                   44160 non-null  float64
 13  Mayo                    44160 non-null  float64
 14  Junio                   44160 non-null

In [ ]:
df_victimas_nacional.columns #obteniendo las columnas del dataset 

Index(['Año', 'Clave_Ent', 'Entidad', 'Bien jurídico afectado',
       'Tipo de delito', 'Subtipo de delito', 'Modalidad', 'Sexo',
       'Rango de edad', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
       'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      dtype='object')

### **Encontrando y limpiando valores NaN.**

In [ ]:
#Identificando los valores perdidos por columna
df_victimas_nacional_NaN = df_victimas_nacional.isna().sum(axis=0)
print(df_victimas_nacional_NaN)

Año                          0
Clave_Ent                    0
Entidad                      0
Bien jurídico afectado       0
Tipo de delito               0
Subtipo de delito            0
Modalidad                    0
Sexo                         0
Rango de edad                0
Enero                        0
Febrero                   7360
Marzo                     7360
Abril                     7360
Mayo                      7360
Junio                     7360
Julio                     7360
Agosto                    7360
Septiembre                7360
Octubre                   7360
Noviembre                 7360
Diciembre                 7360
dtype: int64


In [ ]:
df_victimas_nacional[51520-7360:51520-7357] #Los registros que contienen los valores perdidos son los correspondientes a 2021

Año  Clave_Ent         Entidad  ... Octubre Noviembre Diciembre
44160  2021          1  Aguascalientes  ...     NaN       NaN       NaN
44161  2021          1  Aguascalientes  ...     NaN       NaN       NaN
44162  2021          1  Aguascalientes  ...     NaN       NaN       NaN

[3 rows x 21 columns]

In [ ]:
#Eliminando los valores NaN . Hay que eliminar los registros correspondientes a 2021
#Nos quedamos con el periodo 2015-2020 para realizar el análisis
df_victimas_nacional_2015_2020 = df_victimas_nacional[df_victimas_nacional['Año'] < 2021].copy()

In [ ]:
#Corroboramos que ya no existan valores NaN en el dataset. 
df_victimas_nacional_NaN = df_victimas_nacional_2015_2020.isna().sum(axis=0)
df_victimas_nacional_NaN # El Dataset ya no contiene valores NaN

Año                       0
Clave_Ent                 0
Entidad                   0
Bien jurídico afectado    0
Tipo de delito            0
Subtipo de delito         0
Modalidad                 0
Sexo                      0
Rango de edad             0
Enero                     0
Febrero                   0
Marzo                     0
Abril                     0
Mayo                      0
Junio                     0
Julio                     0
Agosto                    0
Septiembre                0
Octubre                   0
Noviembre                 0
Diciembre                 0
dtype: int64

In [ ]:
#No es necesario resetear el índice ya que eliminamos los últimos valores del dataset. El índice original se conserva 
df_victimas_nacional_2015_2020.tail(3)

Año  Clave_Ent    Entidad  ... Octubre Noviembre Diciembre
44157  2020         32  Zacatecas  ...     1.0       0.0       0.0
44158  2020         32  Zacatecas  ...     0.0       0.0       0.0
44159  2020         32  Zacatecas  ...     0.0       0.0       0.0

[3 rows x 21 columns]

### **Modificando el nombre de las columnas.**

In [ ]:
#Primero cambiaremos todos los nombres de las columnas a minúsculas. 
df_victimas_nacional_2015_2020.columns= df_victimas_nacional_2015_2020.columns.str.strip().str.lower()
df_victimas_nacional_2015_2020.columns

Index(['año', 'clave_ent', 'entidad', 'bien jurídico afectado',
       'tipo de delito', 'subtipo de delito', 'modalidad', 'sexo',
       'rango de edad', 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
       'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
      dtype='object')

In [ ]:
#Es útil modificar el nombre de las columnas a otros que conserven el formato.
#Creamos un diccionario con el nombre de las columnas viejas y nuevas.
nombre_columnas_violencia_nacional = {
    'bien jurídico afectado':'bien_juridico_afectado',
    'tipo de delito':'tipo_de_delito',
    'subtipo de delito':'subtipo_de_delito',
    'rango de edad':'rango_de_edad'
    
}

In [ ]:
#Modificamos el nombre de las columnas del dataframe
df_victimas_nacional_2015_2020_renombrado = df_victimas_nacional_2015_2020.rename(columns=nombre_columnas_violencia_nacional)

In [ ]:
df_victimas_nacional_2015_2020_renombrado.head(3)

año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...     0.0       0.0       0.0
1  2015          1  Aguascalientes  ...     0.0       0.0       0.0
2  2015          1  Aguascalientes  ...     0.0       0.0       0.0

[3 rows x 21 columns]

### **Modificación del dataframe limpio y renombrado.**

In [ ]:
#Es necesario cambiar el tipo de dato de float64 a int64 de los meses Febrero-Diciembre ya que el número de víctimas no puede ser decimal
meses = ['febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
for mes in range(11): 
    df_victimas_nacional_2015_2020_renombrado[meses[mes]] = df_victimas_nacional_2015_2020_renombrado[meses[mes]].astype(int)

In [ ]:
df_victimas_nacional_2015_2020_renombrado.dtypes #Observando los cambios 

año                        int64
clave_ent                  int64
entidad                   object
bien_juridico_afectado    object
tipo_de_delito            object
subtipo_de_delito         object
modalidad                 object
sexo                      object
rango_de_edad             object
enero                      int64
febrero                    int64
marzo                      int64
abril                      int64
mayo                       int64
junio                      int64
julio                      int64
agosto                     int64
septiembre                 int64
octubre                    int64
noviembre                  int64
diciembre                  int64
dtype: object

In [ ]:
df_victimas_nacional_2015_2020_renombrado.head(3) #Este es nuestro dataset 

año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
df_victimas_nacional_2015_2020_renombrado.shape #El tamaño del dataframe 

(44160, 21)

In [ ]:
df_victimas_nacional_2015_2020_renombrado.tipo_de_delito #Podemos observar algunos datos del tipo de delito

0                                                Homicidio
1                                                Homicidio
2                                                Homicidio
3                                                Homicidio
4                                                Homicidio
                               ...                        
44155    Otros delitos que atentan contra la libertad p...
44156                                            Extorsión
44157                                Corrupción de menores
44158                                    Trata de personas
44159                     Otros delitos contra la sociedad
Name: tipo_de_delito, Length: 44160, dtype: object

Como el sexo es el de la víctima, en este caso nos interesan los delitos en 
contra de la **mujer**. 

In [ ]:
 #Estos son los relacionados con víctimas masculinas 
 df_victimas_hombres_nacional_2015_2020 = df_victimas_nacional_2015_2020_renombrado[df_victimas_nacional_2015_2020_renombrado.sexo.str.contains('Hombre')]
 print(df_victimas_hombres_nacional_2015_2020.shape)
 df_victimas_hombres_nacional_2015_2020.head(3)

(17856, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
105  2015          1  Aguascalientes  ...       0         0         0
106  2015          1  Aguascalientes  ...       0         0         0
107  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
#En este dataset se encuentran los homicidios que si fueron víctimas hombres
df_homicidios_nacional_2015_2020 = df_victimas_hombres_nacional_2015_2020[df_victimas_hombres_nacional_2015_2020.tipo_de_delito.str.contains('Homicidio')]
print(df_homicidios_nacional_2015_2020.shape)
df_homicidios_nacional_2015_2020.head(3)

(5184, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
105  2015          1  Aguascalientes  ...       0         0         0
106  2015          1  Aguascalientes  ...       0         0         0
107  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

### **Filtrando la información de víctimas mujeres.**

In [ ]:
#Filtrando la información en las que las víctimas son mujeres. 
df_victimas_mujeres_nacional_2015_2020 = df_victimas_nacional_2015_2020_renombrado[df_victimas_nacional_2015_2020_renombrado.sexo.str.contains('Mujer')]

In [ ]:
# El dataframe filtrado con víctimas mujeres.
print(df_victimas_mujeres_nacional_2015_2020.shape)
df_victimas_mujeres_nacional_2015_2020.head(3)

(20160, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
#Datos correspondientes al tipo de delito de Feminicidio
df_feminicidios_nacional_2015_2020 = df_victimas_mujeres_nacional_2015_2020[df_victimas_mujeres_nacional_2015_2020.tipo_de_delito.str.contains('Feminicidio')]
print(df_feminicidios_nacional_2015_2020.shape)
df_feminicidios_nacional_2015_2020.head(3)

(2304, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
18  2015          1  Aguascalientes  ...       0         0         0
19  2015          1  Aguascalientes  ...       0         0         0
20  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
#Tenemos que corregir los datos de homicidios mal clasificados, ya que al ser mujeres las víctimas corresponde a un feminicidio  
df_homicidios_erroneos = df_victimas_mujeres_nacional_2015_2020[df_victimas_mujeres_nacional_2015_2020.tipo_de_delito.str.contains('Homicidio')]
print(df_homicidios_erroneos.shape)
df_homicidios_erroneos.head(3)

(5184, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
#Corrigiendo los datos de homicidios mal clasificados. Modificando de Homicidio a Feminicidio.
df_homicidios_erroneos_modificados = df_homicidios_erroneos.copy()
df_homicidios_erroneos_modificados.loc[df_homicidios_erroneos_modificados['tipo_de_delito'] == 'Homicidio', 'tipo_de_delito'] = 'Feminicidio'
df_homicidios_erroneos_modificados.head(3)

año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
df_homicidios_erroneos_modificados.subtipo_de_delito #También hay que modificar el subtipo de delito.

0         Homicidio doloso
1         Homicidio doloso
2         Homicidio doloso
3         Homicidio doloso
4        Homicidio culposo
               ...        
44004    Homicidio culposo
44005    Homicidio culposo
44006    Homicidio culposo
44007    Homicidio culposo
44008    Homicidio culposo
Name: subtipo_de_delito, Length: 5184, dtype: object

In [ ]:
#Los datos que podemos encontrar en subtipo de delito son:
print(df_homicidios_erroneos_modificados['subtipo_de_delito'].unique())

['Homicidio doloso' 'Homicidio culposo']


In [ ]:
#Modificando la sección de subtipo de delito cambiando la palabra homicidio por feminicidio.
df_homicidios_erroneos_corregidos = df_homicidios_erroneos_modificados.copy()
df_homicidios_erroneos_corregidos.loc[df_homicidios_erroneos_corregidos['subtipo_de_delito'] == 'Homicidio doloso', 'subtipo_de_delito'] = 'Feminicidio doloso'
df_homicidios_erroneos_corregidos.loc[df_homicidios_erroneos_corregidos['subtipo_de_delito'] == 'Homicidio culposo', 'subtipo_de_delito'] = 'Feminicidio culposo'

df_homicidios_erroneos_corregidos.head(3)

año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

In [ ]:
#Esto es más útil corregirlo en el dataframe original que contiene a las víctimas mujeres. Modificando los datos mal clasificados.
df_victimas_mujeres_nacional_corregido = df_victimas_mujeres_nacional_2015_2020.copy()

#Modificando la sección de tipo_de_delito de Homicidio  a Feminicidio 
df_victimas_mujeres_nacional_corregido.loc[df_victimas_mujeres_nacional_corregido['tipo_de_delito'] == 'Homicidio', 'tipo_de_delito'] = 'Feminicidio'

#Modificando la sección de subtipo de delito 
df_victimas_mujeres_nacional_corregido.loc[df_victimas_mujeres_nacional_corregido['subtipo_de_delito'] == 'Homicidio doloso', 'subtipo_de_delito'] = 'Feminicidio doloso'
df_victimas_mujeres_nacional_corregido.loc[df_victimas_mujeres_nacional_corregido['subtipo_de_delito'] == 'Homicidio culposo', 'subtipo_de_delito'] = 'Feminicidio culposo'

print(df_victimas_mujeres_nacional_corregido.shape)
df_victimas_mujeres_nacional_corregido.head(3)
#¡Listo! Nuestro dataframe ha quedado corregido y listo para realizar análisis exploratorio de datos

(20160, 21)


año  clave_ent         entidad  ... octubre noviembre diciembre
0  2015          1  Aguascalientes  ...       0         0         0
1  2015          1  Aguascalientes  ...       0         0         0
2  2015          1  Aguascalientes  ...       0         0         0

[3 rows x 21 columns]

### **Análisis Exploratorio de Datos.**
Ya tenemos la base de datos limpia y con las columnas deseadas, por lo que es momento de obtener un análisis estadístico y realizar agrupaciones. 

In [ ]:
#La columna de rango de edad contiene los siguientes datos.
print(df_victimas_mujeres_nacional_corregido['rango_de_edad'].unique())

['Menores de edad (0-17)' 'Adultos (18 y más)' 'No especificado']


In [ ]:
#Podemos observar que valores toma la columna de tipo_de_delito 
print(df_victimas_mujeres_nacional_corregido['tipo_de_delito'].unique())

['Feminicidio' 'Lesiones'
 'Otros delitos que atentan contra la vida y la integridad corporal'
 'Secuestro' 'Tráfico de menores' 'Rapto'
 'Otros delitos que atentan contra la libertad personal' 'Extorsión'
 'Corrupción de menores' 'Trata de personas'
 'Otros delitos contra la sociedad']


- En este caso tenemos que agregar una columna que incluya la suma de las víctimas de cada mes para obtener el total de víctimas de ese año. Modificaremos primero el dataset que incluye únicamente los feminicidios bien clasificados.

In [ ]:
#Agreganso la columna que tenga el número de feminicidios de cada año 
meses = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
df_feminicidios_nacional_modificado = df_feminicidios_nacional_2015_2020.copy()
df_feminicidios_nacional_modificado['casos_victimas_anual']=df_feminicidios_nacional_2015_2020[meses].sum(axis=1)
df_feminicidios_nacional_modificado.head(2)

año  clave_ent         entidad  ... noviembre diciembre casos_victimas_anual
18  2015          1  Aguascalientes  ...         0         0                    0
19  2015          1  Aguascalientes  ...         0         0                    0

[2 rows x 22 columns]

In [ ]:
#Observamos el número de feminicidios de cada año.  
df_femicidios = df_feminicidios_nacional_modificado.groupby('año').sum('casos_victimas_anual')
df_femicidios['casos_victimas_anual']

año
2015    426
2016    645
2017    766
2018    914
2019    969
2020    967
Name: casos_victimas_anual, dtype: int64

In [ ]:
# Obtenemos los femenicidios bien clasificados mensuales de cada año en el periodo 2015-2020.
df_femicidios[meses]

enero  febrero  marzo  abril  ...  septiembre  octubre  noviembre  diciembre
año                                 ...                                           
2015     33       30     33     36  ...          45       48         30         40
2016     44       54     70     62  ...          55       48         62         49
2017     51       69     63     62  ...          56       61         58         55
2018     70       69     72     79  ...          78       85         69        100
2019     72       70     82     68  ...          90       70         81         95
2020     75       94     78     73  ...          78       78         88         78

[6 rows x 12 columns]

- Si clasificamos los feminicidios anuales, el año con ***mayor número de feminicidios*** fue **2019**. Sin embargo, el mes con mayor número de casos fue Diciembre de 2018.

In [ ]:
#El número total de feminicidios (bien clasificados) ocurridos durante 2015-2020.
df_feminicidios_nacional_modificado.groupby('tipo_de_delito')['casos_victimas_anual'].sum()

tipo_de_delito
Feminicidio    4687
Name: casos_victimas_anual, dtype: int64

#### **Modificando en el dataframe completo.**
Con esto podremos ver realmente cuántos feminicidios ocurrieron durante 2015-2020. En el dataframe completo tenemos a las víctimas mujeres de todos los tipos de delitos. 

In [ ]:
#Primero tenemos que crear la nueva columna con el acumulado de víctimas de ese año. 
meses = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
df_victimas_mujeres_completo = df_victimas_mujeres_nacional_corregido.copy()
df_victimas_mujeres_completo['casos_victimas_anual']= df_victimas_mujeres_completo[meses].sum(axis=1)
df_victimas_mujeres_completo.head(3)

año  clave_ent         entidad  ... noviembre diciembre casos_victimas_anual
0  2015          1  Aguascalientes  ...         0         0                    0
1  2015          1  Aguascalientes  ...         0         0                    0
2  2015          1  Aguascalientes  ...         0         0                    2

[3 rows x 22 columns]

#### **Feminicidios.**

In [ ]:
#Feminicidios por mes y anuales durante 2015-2020.
df_victimas_mujeres_nacional_delitos = df_victimas_mujeres_completo.groupby(["tipo_de_delito",'año']).sum()
df_victimas_mujeres_nacional_delitos = df_victimas_mujeres_nacional_delitos.loc["Feminicidio"]
meses.append('casos_victimas_anual')
df_victimas_mujeres_nacional_delitos[meses]

enero  febrero  marzo  ...  noviembre  diciembre  casos_victimas_anual
año                          ...                                            
2015    473      480    460  ...        468        472                  5552
2016    411      428    503  ...        492        587                  5972
2017    476      513    548  ...        543        534                  6473
2018    526      557    597  ...        569        617                  6884
2019    534      510    628  ...        589        682                  7127
2020    624      604    625  ...        557        590                  6894

[6 rows x 13 columns]

In [ ]:
#El número total de feminicidios totales ocurridos durante 2015-2020.
feminicidios_2015_2020 = df_victimas_mujeres_nacional_delitos.casos_victimas_anual.sum()
print(f'Han ocurrido {feminicidios_2015_2020} feminicidios durante 2015-2020.')

Han ocurrido 38902 feminicidios durante 2015-2020.


El año con el mayor número de feminicidios fue 2020. Hay una gran diferencia respecto a la cantidad de feminicidios obtenidos con el dataframe con los feminicidios correctamente clasificados.

In [ ]:
#Observamos cuáles son los delitos que cuentan con el mayor número de víctimas durante 2015-2020.
df_victimas_mujeres_delitos_gral.casos_victimas_anual.sort_values(ascending=False)

tipo_de_delito
Lesiones                                                             486891
Otros delitos que atentan contra la libertad personal                 44479
Feminicidio                                                           38902
Extorsión                                                             14461
Otros delitos que atentan contra la vida y la integridad corporal     12208
Corrupción de menores                                                  7544
Otros delitos contra la sociedad                                       5982
Trata de personas                                                      2878
Secuestro                                                              2140
Rapto                                                                  1302
Tráfico de menores                                                      296
Name: casos_victimas_anual, dtype: int64

In [ ]:
#Número total de víctimas mujeres de algún delito.
victimas_mujeres_2015_2020 = df_victimas_mujeres_delitos_gral.casos_victimas_anual.sum()
print(f'Existen {victimas_mujeres_2015_2020} vícitmas mujeres de algún delito durante 2015-2020.')

Existen 617083 vícitmas mujeres de algún delito durante 2015-2020.


In [ ]:
#En la distribución de rangos de edad observamos que la mayor parte corresponden a los No especificado
victimas_por_edad = df_victimas_mujeres_completo.groupby('rango_de_edad').sum()
victimas_por_edad.casos_victimas_anual

rango_de_edad
Adultos (18 y más)        440487
Menores de edad (0-17)     64004
No especificado           112592
Name: casos_victimas_anual, dtype: int64

#### **Víctimas mujeres de cualquier tipo de delito.**

In [ ]:
#Víctimas mujeres de cualquier tipo de delito clasificadas por año. 
df_delitos_mujer = df_victimas_mujeres_completo.groupby(['año','tipo_de_delito'])['casos_victimas_anual'].sum()
df_delitos_mujer = pd.DataFrame(df_delitos_mujer)
df_delitos_mujer

casos_victimas_anual
año  tipo_de_delito                                                          
2015 Corrupción de menores                                               1128
     Extorsión                                                           2091
     Feminicidio                                                         5552
     Lesiones                                                           88629
     Otros delitos contra la sociedad                                     356
...                                                                       ...
2020 Otros delitos que atentan contra la vida y la i...                  3236
     Rapto                                                                150
     Secuestro                                                            224
     Trata de personas                                                    454
     Tráfico de menores                                                     9

[66 rows x 1 columns]

In [ ]:
# Número total de víctimas mujeres al año en el periodo 2015-2020.
victimas_mujeres_cualquier_delito = df_delitos_mujer.groupby('año')['casos_victimas_anual'].sum()
victimas_mujeres_cualquier_delito 

año
2015    105646
2016     99571
2017    101692
2018    100935
2019    111450
2020     97789
Name: casos_victimas_anual, dtype: int64

#### **Clasificación de víctimas mujeres por entidad federativa.** 

In [ ]:
#Es importante analizar la cantidad de víctimas 
df_victimas_mujer_entidad = df_victimas_mujeres_completo.groupby(['entidad'])['casos_victimas_anual'].sum()
df_victimas_mujer_entidad = pd.DataFrame(df_victimas_mujer_entidad.sort_values(ascending=False))
df_victimas_mujer_entidad

casos_victimas_anual
entidad                                              
México                                         153141
Baja California                                 40686
Nuevo León                                      38494
Guanajuato                                      38312
Jalisco                                         38293
Michoacán de Ocampo                             23935
Querétaro                                       20302
Hidalgo                                         19493
Ciudad de México                                18907
Puebla                                          18732
Veracruz de Ignacio de la Llave                 18538
Chihuahua                                       18138
Tamaulipas                                      15989
Coahuila de Zaragoza                            15241
Oaxaca                                          14593
Morelos                                         14540
Guerrero                                        13727
Sinaloa                                         12649
Tabasco                                         11846
Durango                                         11520
San Luis Potosí                                 11465
Zacatecas                                        8445
Sonora                                           8213
Quintana Roo                                     7400
Chiapas                                          6550
Baja California Sur                              5916
Colima                                           3920
Yucatán                                          3743
Tlaxcala                                         1452
Nayarit                                          1343
Campeche                                          960
Aguascalientes                                    600

In [ ]:
#Feminicidios por entidad 
meses = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']
df_victimas_mujeres_nacional_delitos = df_victimas_mujeres_completo.groupby(["tipo_de_delito",'entidad']).sum()
df_victimas_mujeres_nacional_delitos = df_victimas_mujeres_nacional_delitos.loc["Feminicidio"]
meses.append('casos_victimas_anual')
feminicidios_entidad = pd.DataFrame(df_victimas_mujeres_nacional_delitos['casos_victimas_anual'].sort_values(ascending=False))
feminicidios_entidad

casos_victimas_anual
entidad                                              
Guanajuato                                       4180
México                                           3443
Jalisco                                          2327
Michoacán de Ocampo                              2242
Veracruz de Ignacio de la Llave                  2058
Guerrero                                         1944
Baja California                                  1833
Chihuahua                                        1788
Ciudad de México                                 1710
Puebla                                           1681
Nuevo León                                       1569
Tamaulipas                                       1491
Oaxaca                                           1413
Chiapas                                          1232
Sinaloa                                          1004
Sonora                                            989
Hidalgo                                           859
Morelos                                           828
Quintana Roo                                      773
Zacatecas                                         737
Coahuila de Zaragoza                              684
Tabasco                                           652
San Luis Potosí                                   609
Colima                                            538
Querétaro                                         495
Durango                                           399
Aguascalientes                                    311
Nayarit                                           310
Tlaxcala                                          288
Baja California Sur                               248
Campeche                                          172
Yucatán                                            95

## **Conclusiones**


---




En el tema de violencia de género, México se encuentra en un escenario preocupante debido a que los reportes relacionados a acoso sexual/violencia de genero/violación han ido en aumentando año con año. Si bien el número máximo de feminicidios en México fue en 2019 con 7,127 víctimas, las llamadas recibidas a LOCATEL por violencia de género en la CDMX aumentaron durante el aislamiento, llegando a su máximo con 24,500 llamadas en 2020, las razones de la llamada más frecuentes fueron: delitos contra la integridad familiar, violencia de género y contra la paz y seguridad. Esto indicándonos que la mujer se encontraba en aislamiento con su agresor(a).En temas de situación social, la escolaridad de las víctimas de las llamadas representan bachillerato 40.6% , secundaria 31% y 17.5% licenciatura. Sus ocupaciones: empleada 42.7% , ama de casa 34.2%  y comerciante 6.4%:
El de las víctimas eran solteras 56.2% , casadas 30.5% y en unión libre 12.2%.
 
El estado donde más se ven a las mujeres desaparecidas por última vez es CDMX, seguido de Tamaulipas y Puebla.Mientas que el Estado de México cuenta con el mayor número de víctimas por cualquier delito( 153,141 víctimas) y en feminicidios encabeza Guanajuato con 4,180 víctimas. En el caso de la CDMX Iztapalapa seguirá siendo la alcaldía donde se comete el mayor número de delitos contra la mujer.

Estos datos son preocupantes y son un llamado urgente de atención a tomar medidas y soluciones en este tema para erradicar la desigualdad de género y la violencia contra la mujer.

##**Referencias.** 


---


1.  Organización Mundial de la Salud,OMS(2017).**Violencia contra la mujer.** Recuperado de:  https://www.who.int/es/news-room/fact-sheets/detail/violence-against-women. Consultado el : 06 de marzo de 2021.
2.   ONU Mujeres,México(2018).**La violencia contra las mujeres no es normal ni tolerable. Garantizar los derechos humanos de las mujeres y las niñas es trabajo de todas y de todos.**Recuperado de: https://mexico.unwomen.org/es/noticias-y-eventos/articulos/2018/11/violencia-contra-las-mujeres. Consultado el : 06 de marzo de 2021. 
3. Moctezuma, D. Narro,J.Orozco,L (2014).**La mujer en México: inequidad, pobreza y violencia**.*Revista Mexicana de Ciencias Políticas y Sociales*. Volumen 59,p.117-146.Recuperado de: https://www.sciencedirect.com/science/article/pii/S0185191814708037. Consultado el 07 de marzo de 2021.




##**Fuentes para los Datasets.**

---
I. Gobierno de la Ciudad de México, Portal de datos abiertos (12 de enero de 2021).**Servicios para la población en general (antes Llamadas realizadas a Línea Mujeres)**. Recopilada de: https://datos.cdmx.gob.mx/dataset/servicios-para-la-poblacion-en-general/resource/59af003e-042e-4aeb-b4f0-8ca9a6600ec4. Consultada el 04 de marzo de 2021.

II. Gobierno de la Ciudad de México, Portal de datos abiertos(12 de enero de 2021). **Carpetas de investigación FGJ de la Ciudad de México**. Recopilada de: https://datos.cdmx.gob.mx/dataset/carpetas-de-investigacion-fgj-de-la-ciudad-de-mexico#.  Consultada el 04 de marzo de 2021.

III. Gobierno de la Ciudad de México, Portal de datos abiertos (12 de enero de 2021). **Víctimas en carpetas de investigación FGJ**. Recopilada de : https://datos.cdmx.gob.mx/dataset/victimas-en-carpetas-de-investigacion-fgj. Consultada el 04 de marzo de 2021.

IV. Gobierno de México. Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública (20 de febrero de 2021).**Datos Abiertos de Incidencia Delictiva. Reportes de incidencia delictiva al mes de enero 2021 (Nueva metodología).** Recopilado de: https://www.gob.mx/sesnsp/acciones-y-programas/datos-abiertos-de-incidencia-delictiva. Consultada el 10 de marzo de 2021.

V. Gobierno de México. Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública (31 de mayo de 2018).**Registro Nacional de Datos de Personas Extraviadas o Desaparecidas, RNPED**. Recopliado de: https://www.gob.mx/sesnsp/acciones-y-programas/registro-nacional-de-datos-de-personas-extraviadas-o-desaparecidas-rnped . Consultado el 09 de marzo de 2021.

